(asdf:defsystem "sbcl-agent"
  :description "An environment based agentic first development enviornment"
  :author "Paul Bernard"
  :license "Apache-2.0"
  :version "0.1.0"
  :serial t
  :depends-on ()
  :components ((:file "src/package")
               (:file "src/config")
               (:file "src/json")
               (:file "src/provider-protocol")
               (:file "src/provider-transport")
               (:file "src/provider-transport-curl")
               (:file "src/retrieval-intent")
               (:file "src/retrieval-plan")
               (:file "src/retrieval-ranking")
               (:file "src/retrieval-dossier")
               (:file "src/retrieval-service")
               (:file "src/reasoning-brief")
               (:file "src/planning-brief")
               (:file "src/outcome-brief")
               (:file "src/prior-outcome-reuse")
               (:file "src/cognition-bundle")
               (:file "src/request-snapshot")
               (:file "src/provider-mock")
               (:file "src/provider-openai")
               (:file "src/commands")
               (:file "src/events")
               (:file "src/conversation")
               (:file "src/policy")
               (:file "src/session")
               (:file "src/environment-core")
               (:file "src/runtime-state")
               (:file "src/conversation-state")
               (:file "src/workflow-state")
               (:file "src/artifact-state")
               (:file "src/environment-sync")
               (:file "src/environment-summary")
               (:file "src/environment-store")
               (:file "src/environment-compatibility")
               (:file "src/environment")
               (:file "src/workflow")
               (:file "src/work-items")
               (:file "src/integration-rgp")
               (:file "src/incidents")
               (:file "src/sandbox")
               (:file "src/tools-registry")
               (:file "src/tools-fs")
               (:file "src/tools-session")
               (:file "src/tools-runtime")
               (:file "src/tools-docs")
               (:file "src/tools-process")
               (:file "src/tools-git")
               (:file "src/patch")
               (:file "src/tasks")
               (:file "src/mutation-engine")
               (:file "src/service-core")
               (:file "src/environment-service")
               (:file "src/conversation-service")
               (:file "src/runtime-service")
               (:file "src/workflow-service")
               (:file "src/approval-service")
               (:file "src/session-service")
               (:file "src/work-item-service")
               (:file "src/incident-service")
               (:file "src/task-service")
               (:file "src/worker-service")
               (:file "src/workflow-ops-service")
               (:file "src/rgp-service")
               (:file "src/mutation-review-service")
               (:file "src/event-service")
               (:file "src/execution-service")
               (:file "src/turn-orchestrator")
               (:file "src/shell")
               (:file "src/repl")
               (:file "src/main"))
  :in-order-to ((asdf:test-op (asdf:test-op "sbcl-agent/tests"))))

(asdf:defsystem "sbcl-agent/tests"
  :description "Base test suite for sbcl-agent."
  :author "Paul Bernard"
  :license "Apache-2.0"
  :depends-on ("sbcl-agent")
  :serial t
  :components ((:file "tests/package")
               (:file "tests/support")
               (:file "tests/provider-support")
               (:file "tests/smoke")
               (:file "tests/provider-context")
               (:file "tests/retrieval")
               (:file "tests/evals")
               (:file "tests/service-contracts")
               (:file "tests/test-runner")
               (:file "tests/performance"))
  :perform (asdf:test-op (op c)
             (declare (ignore op c))
             (uiop:symbol-call :sbcl-agent/tests :run-all-tests)))
