(in-package #:sbcl-agent/tests)

(defun run-test-case (name thunk)
  (funcall thunk)
  (format t "PASS ~A~%" name))

(defun run-test-group (cases)
  (dolist (case cases)
    (run-test-case (first case) (second case))))

(defun annotate-test-cases (category cases)
  (mapcar (lambda (case)
            (list :name (first case)
                  :thunk (second case)
                  :category category))
          cases))

(defun annotate-derived-test-cases (classifier cases)
  (mapcar (lambda (case)
            (list :name (first case)
                  :thunk (second case)
                  :category (funcall classifier (first case))))
          cases))

(defun catalog-case-name (case)
  (getf case :name))

(defun catalog-case-thunk (case)
  (getf case :thunk))

(defun catalog-case-category (case)
  (getf case :category))

(defun test-name-contains-p (name needle)
  (not (null (search needle name :test #'char-equal))))

(defun extended-suite-test-category (name)
  (cond
    ((or (test-name-contains-p name "retrieval")
         (test-name-contains-p name "grounding")
         (test-name-contains-p name "memory")
         (test-name-contains-p name "playbook")
         (test-name-contains-p name "evaluation-harness")
         (test-name-contains-p name "outcome-brief")
         (test-name-contains-p name "reasoning-brief")
         (test-name-contains-p name "planning-brief"))
     :retrieval-and-memory)
    ((test-name-contains-p name "service-contract")
     :service-contracts)
    ((or (test-name-contains-p name "orchestration")
         (test-name-contains-p name "long-horizon")
         (test-name-contains-p name "decomposition")
         (test-name-contains-p name "turn-flow"))
     :orchestration-and-planning)
    ((or (test-name-contains-p name "task")
         (test-name-contains-p name "worker"))
     :task-and-worker-lifecycle)
    ((or (test-name-contains-p name "workflow")
         (test-name-contains-p name "work-item")
         (test-name-contains-p name "approval")
         (test-name-contains-p name "validator")
         (test-name-contains-p name "replay")
         (test-name-contains-p name "reconcile")
         (test-name-contains-p name "checkpoint")
         (test-name-contains-p name "why-waiting")
         (test-name-contains-p name "transaction-replay")
         (test-name-contains-p name "capability-policy")
         (test-name-contains-p name "capability-grant"))
     :workflow-and-governance)
    ((or (test-name-contains-p name "environment")
         (test-name-contains-p name "session")
         (test-name-contains-p name "persistence")
         (test-name-contains-p name "serializable")
         (test-name-contains-p name "load-"))
     :environment-and-persistence)
    ((or (test-name-contains-p name "runtime")
         (test-name-contains-p name "incident")
         (test-name-contains-p name "mutation-review")
         (test-name-contains-p name "recovery")
         (test-name-contains-p name "artifact"))
     :runtime-and-incidents)
    ((or (test-name-contains-p name "compatibility")
         (test-name-contains-p name "linux-app")
         (test-name-contains-p name "execution-shell")
         (test-name-contains-p name "shell-workspace")
         (test-name-contains-p name "operator-status")
         (test-name-contains-p name "doctor-command"))
     :shell-and-compatibility)
    ((or (test-name-contains-p name "list-tools")
         (test-name-contains-p name "docs-read")
         (test-name-contains-p name "fs-read")
         (test-name-contains-p name "proc-run")
         (test-name-contains-p name "approve-and-run-tool")
         (test-name-contains-p name "git-"))
     :tools-and-artifacts)
    (t
     :extended-suite)))

(defun core-and-cli-tests ()
  (list (list "runtime-smoke-test" #'runtime-smoke-test)
        (list "common-lisp-package-bootstrap-test" #'common-lisp-package-bootstrap-test)
        (list "direct-sandbox-tool-wrapper-test" #'direct-sandbox-tool-wrapper-test)
        (list "repl-alias-test" #'repl-alias-test)
        (list "main-command-helper-test" #'main-command-helper-test)
        (list "openai-helper-coverage-test" #'openai-helper-coverage-test)
        (list "json-helper-coverage-test" #'json-helper-coverage-test)
        (list "sandbox-helper-coverage-test" #'sandbox-helper-coverage-test)
        (list "tool-helper-coverage-test" #'tool-helper-coverage-test)
        (list "policy-helper-coverage-test" #'policy-helper-coverage-test)
        (list "openai-provider-io-coverage-test" #'openai-provider-io-coverage-test)
        (list "provider-protocol-helper-coverage-test" #'provider-protocol-helper-coverage-test)
        (list "sandbox-main-coverage-test" #'sandbox-main-coverage-test)
        (list "turn-orchestrator-helper-coverage-test" #'turn-orchestrator-helper-coverage-test)
        (list "shell-helper-coverage-test" #'shell-helper-coverage-test)
        (list "shell-stream-rendering-coverage-test" #'shell-stream-rendering-coverage-test)
        (list "turn-orchestrator-run-coverage-test" #'turn-orchestrator-run-coverage-test)
        (list "conversation-helper-coverage-test" #'conversation-helper-coverage-test)
        (list "sandbox-branch-coverage-test" #'sandbox-branch-coverage-test)
        (list "json-roundtrip-test" #'json-roundtrip-test)
        (list "provider-decode-test" #'provider-decode-test)
        (list "mock-provider-helper-coverage-test" #'mock-provider-helper-coverage-test)
        (list "mock-project-authoring-conversation-approval-test"
              #'mock-project-authoring-conversation-approval-test)
        (list "openai-provider-selection-test" #'openai-provider-selection-test)
        (list "multi-vendor-provider-selection-test" #'multi-vendor-provider-selection-test)
        (list "config-key-file-fallback-test" #'config-key-file-fallback-test)
        (list "config-auto-provider-selection-test" #'config-auto-provider-selection-test)
        (list "config-legacy-key-filename-test" #'config-legacy-key-filename-test)
        (list "config-anthropic-key-file-test" #'config-anthropic-key-file-test)
        (list "config-with-overrides-test" #'config-with-overrides-test)
        (list "config-helper-coverage-test" #'config-helper-coverage-test)
        (list "provider-defaults-coverage-test" #'provider-defaults-coverage-test)
        (list "test-program-reporting-coverage-test" #'test-program-reporting-coverage-test)
        (list "test-program-category-runner-coverage-test" #'test-program-category-runner-coverage-test)
        (list "test-program-harness-inventory-coverage-test" #'test-program-harness-inventory-coverage-test)
        (list "openai-request-model-selection-test" #'openai-request-model-selection-test)
        (list "invalid-eval-action-dropped-test" #'invalid-eval-action-dropped-test)
        (list "chat-argument-parsing-test" #'chat-argument-parsing-test)
        (list "command-normalization-test" #'command-normalization-test)
        (list "provider-cli-command-test" #'provider-cli-command-test)
        (list "platform-cli-command-test" #'platform-cli-command-test)
        (list "provider-profile-shell-commands-test" #'provider-profile-shell-commands-test)
        (list "platform-shell-commands-test" #'platform-shell-commands-test)
        (list "provider-auto-routing-selection-test" #'provider-auto-routing-selection-test)
        (list "provider-governance-routing-selection-test" #'provider-governance-routing-selection-test)
        (list "rgp-integration-snapshot-test" #'rgp-integration-snapshot-test)
        (list "rgp-integration-shell-commands-test" #'rgp-integration-shell-commands-test)
        (list "shell-eval-test" #'shell-eval-test)))

(defun provider-and-conversation-tests ()
  (list (list "ask-dispatch-test" #'ask-dispatch-test)
        (list "say-dispatch-test" #'say-dispatch-test)
        (list "say-mixed-action-operations-test" #'say-mixed-action-operations-test)
        (list "say-patch-action-approval-test" #'say-patch-action-approval-test)
        (list "say-patch-action-deferred-by-incident-test" #'say-patch-action-deferred-by-incident-test)
        (list "say-weakly-grounded-patch-deferred-test" #'say-weakly-grounded-patch-deferred-test)
        (list "strategy-governed-mutation-deferred-test" #'strategy-governed-mutation-deferred-test)
        (list "say-mutating-eval-approval-test" #'say-mutating-eval-approval-test)
        (list "say-git-write-tool-approval-test" #'say-git-write-tool-approval-test)
        (list "streaming-provider-test" #'streaming-provider-test)
        (list "provider-event-normalization-test" #'provider-event-normalization-test)
        (list "event-envelope-correlation-fields-test" #'event-envelope-correlation-fields-test)
        (list "event-family-normalization-coverage-test" #'event-family-normalization-coverage-test)
        (list "openai-stream-line-parser-test" #'openai-stream-line-parser-test)
        (list "openai-stream-response-decode-test" #'openai-stream-response-decode-test)
        (list "streaming-ask-dispatch-test" #'streaming-ask-dispatch-test)
        (list "default-streaming-ask-dispatch-test" #'default-streaming-ask-dispatch-test)
        (list "chat-interactive-flag-test" #'chat-interactive-flag-test)
        (list "assistant-action-proposal-test" #'assistant-action-proposal-test)
        (list "assistant-action-staging-test" #'assistant-action-staging-test)
        (list "assistant-mixed-action-ask-test" #'assistant-mixed-action-ask-test)
        (list "assistant-action-execution-test" #'assistant-action-execution-test)
        (list "assistant-eval-action-execution-test" #'assistant-eval-action-execution-test)
        (list "direct-conversation-runtime-eval-routing-test" #'direct-conversation-runtime-eval-routing-test)
        (list "conversation-runtime-eval-confirmation-routing-test" #'conversation-runtime-eval-confirmation-routing-test)
        (list "pasted-assistant-action-command-test" #'pasted-assistant-action-command-test)
        (list "journal-date-time-followup-execution-test" #'journal-date-time-followup-execution-test)
        (list "session-summary-recent-transcript-test" #'session-summary-recent-transcript-test)
        (list "provider-session-summary-compact-test" #'provider-session-summary-compact-test)
        (list "environment-provider-context-precedence-test" #'environment-provider-context-precedence-test)
        (list "provider-request-context-test" #'provider-request-context-test)
        (list "provider-rendering-context-test" #'provider-rendering-context-test)
        (list "provider-rendering-governance-ready-test" #'provider-rendering-governance-ready-test)
        (list "provider-request-single-environment-snapshot-test" #'provider-request-single-environment-snapshot-test)
        (list "provider-context-bundle-consistency-test" #'provider-context-bundle-consistency-test)
        (list "provider-request-snapshot-conversion-test" #'provider-request-snapshot-conversion-test)
        (list "provider-summaries-prefer-environment-snapshot-domains-test" #'provider-summaries-prefer-environment-snapshot-domains-test)
        (list "provider-context-defaults-prefer-environment-conversation-state-test" #'provider-context-defaults-prefer-environment-conversation-state-test)
        (list "provider-policy-and-operator-summary-prefer-snapshot-test" #'provider-policy-and-operator-summary-prefer-snapshot-test)
        (list "provider-summary-does-not-require-session-resync-test" #'provider-summary-does-not-require-session-resync-test)
        (list "thread-shell-commands-test" #'thread-shell-commands-test)
        (list "thread-show-and-turn-status-test" #'thread-show-and-turn-status-test)
        (list "turn-status-approval-summary-test" #'turn-status-approval-summary-test)
        (list "turn-resume-approval-flow-test" #'turn-resume-approval-flow-test)
        (list "turn-resume-isolates-pending-actions-by-turn-test" #'turn-resume-isolates-pending-actions-by-turn-test)
        (list "turn-resume-validation-first-followup-test" #'turn-resume-validation-first-followup-test)
        (list "turn-resume-provider-followup-test" #'turn-resume-provider-followup-test)))

(defun interaction-boundary-tests ()
  (list (list "interaction-decision-conversation-only-test" #'interaction-decision-conversation-only-test)
        (list "interaction-decision-inspection-only-test" #'interaction-decision-inspection-only-test)
        (list "interaction-decision-prepare-without-write-test" #'interaction-decision-prepare-without-write-test)
        (list "interaction-decision-direct-mutation-test" #'interaction-decision-direct-mutation-test)
        (list "interaction-decision-resume-existing-work-test" #'interaction-decision-resume-existing-work-test)
        (list "interaction-decision-ambiguous-safe-default-test" #'interaction-decision-ambiguous-safe-default-test)))

(defun extended-suite-tests ()
  (list
   (list "retrieval-intent-runtime-debugging-test" #'retrieval-intent-runtime-debugging-test)
   (list "retrieval-intent-code-change-test" #'retrieval-intent-code-change-test)
   (list "retrieval-intent-testing-feedback-test" #'retrieval-intent-testing-feedback-test)
   (list "retrieval-intent-project-governance-test" #'retrieval-intent-project-governance-test)
   (list "retrieval-intent-alignment-analysis-test" #'retrieval-intent-alignment-analysis-test)
   (list "retrieval-plan-compact-first-test" #'retrieval-plan-compact-first-test)
   (list "retrieval-plan-expand-on-gap-test" #'retrieval-plan-expand-on-gap-test)
   (list "retrieval-plan-governance-bias-test" #'retrieval-plan-governance-bias-test)
   (list "retrieval-dossier-auto-expansion-test" #'retrieval-dossier-auto-expansion-test)
   (list "retrieval-dossier-no-auto-expansion-compact-test" #'retrieval-dossier-no-auto-expansion-compact-test)
   (list "retrieval-dossier-governance-bias-test" #'retrieval-dossier-governance-bias-test)
   (list "retrieval-plan-semantic-ranking-history-test" #'retrieval-plan-semantic-ranking-history-test)
   (list "retrieval-dossier-runtime-debugging-test" #'retrieval-dossier-runtime-debugging-test)
   (list "retrieval-dossier-service-contract-test" #'retrieval-dossier-service-contract-test)
   (list "retrieval-dossier-testing-context-test" #'retrieval-dossier-testing-context-test)
   (list "retrieval-dossier-project-context-test" #'retrieval-dossier-project-context-test)
   (list "retrieval-dossier-intent-context-test" #'retrieval-dossier-intent-context-test)
   (list "alignment-context-packet-service-test" #'alignment-context-packet-service-test)
   (list "alignment-state-service-test" #'alignment-state-service-test)
   (list "retrieval-ranking-history-dossier-test" #'retrieval-ranking-history-dossier-test)
   (list "retrieval-ranking-governance-bias-test" #'retrieval-ranking-governance-bias-test)
   (list "retrieval-ranking-disabled-guardrail-test" #'retrieval-ranking-disabled-guardrail-test)
   (list "evaluation-harness-smoke-test" #'evaluation-harness-smoke-test)
   (list "reasoning-brief-grounding-test" #'reasoning-brief-grounding-test)
   (list "planning-brief-grounding-test" #'planning-brief-grounding-test)
   (list "validation-plan-grounding-test" #'validation-plan-grounding-test)
   (list "retrieval-focus-plan-grounding-test" #'retrieval-focus-plan-grounding-test)
   (list "action-agenda-grounding-test" #'action-agenda-grounding-test)
   (list "outcome-brief-grounding-test" #'outcome-brief-grounding-test)
   (list "prior-outcome-brief-reuse-test" #'prior-outcome-brief-reuse-test)
   (list "turn-outcome-memory-recording-test" #'turn-outcome-memory-recording-test)
   (list "durable-memory-prior-outcome-reuse-test" #'durable-memory-prior-outcome-reuse-test)
   (list "durable-playbook-synthesis-test" #'durable-playbook-synthesis-test)
   (list "fresh-session-playbook-reuse-test" #'fresh-session-playbook-reuse-test)
   (list "playbook-ranking-prefers-category-and-history-test" #'playbook-ranking-prefers-category-and-history-test)
   (list "durable-failure-cluster-synthesis-test" #'durable-failure-cluster-synthesis-test)
   (list "fresh-session-self-improvement-brief-test" #'fresh-session-self-improvement-brief-test)
   (list "evaluation-report-memory-recording-test" #'evaluation-report-memory-recording-test)
   (list "evaluation-failure-self-improvement-brief-test" #'evaluation-failure-self-improvement-brief-test)
   (list "governed-turn-persists-long-horizon-plan-test" #'governed-turn-persists-long-horizon-plan-test)
   (list "long-horizon-resume-payload-flow-test" #'long-horizon-resume-payload-flow-test)
   (list "long-horizon-plan-steering-test" #'long-horizon-plan-steering-test)
   (list "long-horizon-validation-revision-test" #'long-horizon-validation-revision-test)
   (list "long-horizon-incident-revision-test" #'long-horizon-incident-revision-test)
   (list "durable-decomposition-playbook-synthesis-test" #'durable-decomposition-playbook-synthesis-test)
   (list "decomposition-playbook-reuse-test" #'decomposition-playbook-reuse-test)
   (list "parallel-orchestration-group-metadata-test" #'parallel-orchestration-group-metadata-test)
   (list "parallel-orchestration-worker-flow-test" #'parallel-orchestration-worker-flow-test)
   (list "parallel-orchestration-review-posture-test" #'parallel-orchestration-review-posture-test)
   (list "orchestration-playbook-reuse-test" #'orchestration-playbook-reuse-test)
   (list "cautious-execution-strategy-grounding-test" #'cautious-execution-strategy-grounding-test)
   (list "retrieval-aware-turn-flow-test" #'retrieval-aware-turn-flow-test)
   (list "post-mutation-retrieval-dossier-service-contract-test" #'post-mutation-retrieval-dossier-service-contract-test)
   (list "service-envelope-helper-test" #'service-envelope-helper-test)
   (list "environment-service-contract-test" #'environment-service-contract-test)
   (list "environment-desktop-preferences-service-contract-test" #'environment-desktop-preferences-service-contract-test)
   (list "environment-image-service-contract-test" #'environment-image-service-contract-test)
   (list "environment-provider-service-contract-test" #'environment-provider-service-contract-test)
   (list "intent-service-contract-test" #'intent-service-contract-test)
   (list "reconciliation-correction-service-contract-test" #'reconciliation-correction-service-contract-test)
   (list "project-service-contract-test" #'project-service-contract-test)
   (list "project-authoring-tool-service-contract-test" #'project-authoring-tool-service-contract-test)
   (list "project-create-conversation-service-contract-test" #'project-create-conversation-service-contract-test)
   (list "project-augment-conversation-service-contract-test" #'project-augment-conversation-service-contract-test)
   (list "trace-link-service-contract-test" #'trace-link-service-contract-test)
   (list "project-command-service-contract-test" #'project-command-service-contract-test)
   (list "conversation-service-contract-test" #'conversation-service-contract-test)
   (list "runtime-service-contract-test" #'runtime-service-contract-test)
   (list "calculator-service-contract-test" #'calculator-service-contract-test)
   (list "kernel-service-contract-test" #'kernel-service-contract-test)
   (list "platform-service-contract-test" #'platform-service-contract-test)
   (list "workflow-and-approval-service-contract-test" #'workflow-and-approval-service-contract-test)
   (list "event-stream-service-contract-test" #'event-stream-service-contract-test)
   (list "incident-and-work-item-service-contract-test" #'incident-and-work-item-service-contract-test)
   (list "runtime-read-and-environment-command-service-contract-test" #'runtime-read-and-environment-command-service-contract-test)
   (list "session-service-contract-test" #'session-service-contract-test)
   (list "shell-service-contract-test" #'shell-service-contract-test)
   (list "execution-service-contract-test" #'execution-service-contract-test)
   (list "interaction-state-boundary-service-contract-test" #'interaction-state-boundary-service-contract-test)
   (list "conversation-execution-end-to-end-scenario-service-contract-test" #'conversation-execution-end-to-end-scenario-service-contract-test)
   (list "mutation-review-and-rgp-service-contract-test" #'mutation-review-and-rgp-service-contract-test)
   (list "task-worker-and-workflow-ops-service-contract-test" #'task-worker-and-workflow-ops-service-contract-test)
   (list "ask-enqueue-test" #'ask-enqueue-test)
   (list "queued-ask-worker-test" #'queued-ask-worker-test)
   (list "describe-task-progress-test" #'describe-task-progress-test)
   (list "monitor-task-test" #'monitor-task-test)
   (list "task-monitoring-prefers-environment-agent-state-test" #'task-monitoring-prefers-environment-agent-state-test)
   (list "task-queue-test" #'task-queue-test)
   (list "enqueue-task-updates-environment-agent-state-test" #'enqueue-task-updates-environment-agent-state-test)
   (list "task-run-next-test" #'task-run-next-test)
   (list "task-cancel-test" #'task-cancel-test)
   (list "worker-flow-test" #'worker-flow-test)
   (list "worker-mutations-update-environment-agent-state-test" #'worker-mutations-update-environment-agent-state-test)
   (list "worker-introspection-test" #'worker-introspection-test)
   (list "worker-monitoring-prefers-environment-agent-state-test" #'worker-monitoring-prefers-environment-agent-state-test)
   (list "work-item-creation-test" #'work-item-creation-test)
   (list "work-item-persistence-test" #'work-item-persistence-test)
   (list "work-item-checkpoint-test" #'work-item-checkpoint-test)
   (list "work-item-shell-commands-test" #'work-item-shell-commands-test)
   (list "work-item-plan-shell-commands-test" #'work-item-plan-shell-commands-test)
   (list "work-item-validation-test" #'work-item-validation-test)
   (list "work-item-failure-validation-test" #'work-item-failure-validation-test)
   (list "work-item-provenance-test" #'work-item-provenance-test)
   (list "work-item-provenance-shell-test" #'work-item-provenance-shell-test)
   (list "work-item-taint-reconciliation-test" #'work-item-taint-reconciliation-test)
   (list "validation-and-reconciliation-event-correlation-test" #'validation-and-reconciliation-event-correlation-test)
   (list "work-item-taint-shell-test" #'work-item-taint-shell-test)
   (list "workflow-record-creation-test" #'workflow-record-creation-test)
   (list "workflow-record-persistence-test" #'workflow-record-persistence-test)
   (list "workflow-record-shell-test" #'workflow-record-shell-test)
   (list "workflow-record-approval-state-test" #'workflow-record-approval-state-test)
   (list "execution-shell-commands-test" #'execution-shell-commands-test)
   (list "compatibility-shell-commands-test" #'compatibility-shell-commands-test)
   (list "linux-app-compatibility-kernel-test" #'linux-app-compatibility-kernel-test)
   (list "compatibility-app-registry-shell-test" #'compatibility-app-registry-shell-test)
   (list "shell-workspace-commands-test" #'shell-workspace-commands-test)
   (list "workflow-record-quarantine-resume-test" #'workflow-record-quarantine-resume-test)
   (list "workflow-milestone-event-correlation-test" #'workflow-milestone-event-correlation-test)
   (list "workflow-record-operator-shell-test" #'workflow-record-operator-shell-test)
   (list "work-item-wait-report-test" #'work-item-wait-report-test)
   (list "why-waiting-shell-command-test" #'why-waiting-shell-command-test)
   (list "workflow-record-resume-payload-test" #'workflow-record-resume-payload-test)
   (list "session-wait-summary-test" #'session-wait-summary-test)
   (list "session-wait-summary-prefers-environment-workflow-state-test" #'session-wait-summary-prefers-environment-workflow-state-test)
   (list "checkpoint-linked-resume-payload-test" #'checkpoint-linked-resume-payload-test)
   (list "transaction-replay-id-test" #'transaction-replay-id-test)
   (list "validator-action-plan-test" #'validator-action-plan-test)
   (list "validator-task-records-test" #'validator-task-records-test)
   (list "list-replay-groups-command-test" #'list-replay-groups-command-test)
   (list "replay-groups-prefer-environment-workflow-state-test" #'replay-groups-prefer-environment-workflow-state-test)
   (list "list-image-reconciliations-command-test" #'list-image-reconciliations-command-test)
   (list "image-reconciliations-prefer-environment-workflow-state-test" #'image-reconciliations-prefer-environment-workflow-state-test)
   (list "replay-validator-set-mixed-status-test" #'replay-validator-set-mixed-status-test)
   (list "replay-validator-set-command-test" #'replay-validator-set-command-test)
   (list "validator-failure-status-test" #'validator-failure-status-test)
   (list "replay-validator-task-command-test" #'replay-validator-task-command-test)
   (list "reconcile-image-only-source-command-test" #'reconcile-image-only-source-command-test)
   (list "session-replay-group-summary-test" #'session-replay-group-summary-test)
   (list "image-reconciliation-record-test" #'image-reconciliation-record-test)
   (list "session-image-reconciliation-summary-test" #'session-image-reconciliation-summary-test)
   (list "image-only-outcome-test" #'image-only-outcome-test)
   (list "operator-status-summary-test" #'operator-status-summary-test)
   (list "operator-status-tool-test" #'operator-status-tool-test)
   (list "doctor-command-wait-summary-test" #'doctor-command-wait-summary-test)
   (list "doctor-command-replay-and-reconciliation-test" #'doctor-command-replay-and-reconciliation-test)
   (list "task-persistence-test" #'task-persistence-test)
   (list "session-plan-test" #'session-plan-test)
   (list "capability-policy-model-test" #'capability-policy-model-test)
   (list "capability-grant-session-test" #'capability-grant-session-test)
   (list "session-save-load-test" #'session-save-load-test)
   (list "serializable-session-copy-trims-transcript-test" #'serializable-session-copy-trims-transcript-test)
   (list "project-record-persistence-test" #'project-record-persistence-test)
   (list "environment-creation-test" #'environment-creation-test)
   (list "environment-persistence-test" #'environment-persistence-test)
   (list "environment-provider-key-file-behavior-test"
         #'environment-provider-key-file-behavior-test)
   (list "environment-serializes-compatibility-payload-test" #'environment-serializes-compatibility-payload-test)
   (list "compatibility-payload-reconstructs-legacy-session-header-test" #'compatibility-payload-reconstructs-legacy-session-header-test)
   (list "serializable-environment-copy-preserves-existing-compatibility-payload-test" #'serializable-environment-copy-preserves-existing-compatibility-payload-test)
   (list "load-environment-normalizes-legacy-compatibility-session-test" #'load-environment-normalizes-legacy-compatibility-session-test)
   (list "environment-serializable-copy-trims-derived-indexes-test" #'environment-serializable-copy-trims-derived-indexes-test)
   (list "load-environment-rehydrates-derived-indexes-test" #'load-environment-rehydrates-derived-indexes-test)
   (list "load-environment-rehydrates-session-events-and-transcript-test" #'load-environment-rehydrates-session-events-and-transcript-test)
   (list "load-environment-rehydrates-pending-actions-test" #'load-environment-rehydrates-pending-actions-test)
   (list "load-environment-rehydrates-incidents-test" #'load-environment-rehydrates-incidents-test)
   (list "load-environment-rehydrates-tasks-and-workers-test" #'load-environment-rehydrates-tasks-and-workers-test)
   (list "load-environment-rehydrates-capability-grants-test" #'load-environment-rehydrates-capability-grants-test)
   (list "load-environment-rehydrates-plan-test" #'load-environment-rehydrates-plan-test)
   (list "load-environment-derives-compatibility-header-from-environment-test" #'load-environment-derives-compatibility-header-from-environment-test)
   (list "environment-workflow-rehydration-test" #'environment-workflow-rehydration-test)
   (list "environment-workflow-write-through-test" #'environment-workflow-write-through-test)
   (list "environment-workflow-event-write-through-test" #'environment-workflow-event-write-through-test)
   (list "environment-event-envelope-test" #'environment-event-envelope-test)
   (list "environment-transcript-event-preserves-full-payload-test" #'environment-transcript-event-preserves-full-payload-test)
   (list "incident-environment-event-projection-test" #'incident-environment-event-projection-test)
   (list "environment-domain-summary-test" #'environment-domain-summary-test)
   (list "environment-runtime-domain-summary-helper-test" #'environment-runtime-domain-summary-helper-test)
   (list "environment-conversation-domain-summary-helper-test" #'environment-conversation-domain-summary-helper-test)
   (list "environment-workflow-domain-summary-helper-test" #'environment-workflow-domain-summary-helper-test)
   (list "environment-artifact-domain-helper-test" #'environment-artifact-domain-helper-test)
   (list "environment-summary-prefers-domain-state-test" #'environment-summary-prefers-domain-state-test)
   (list "environment-summary-does-not-resync-on-read-test" #'environment-summary-does-not-resync-on-read-test)
  (list "environment-summary-alignment-state-test" #'environment-summary-alignment-state-test)
  (list "reconciliation-decision-service-test" #'reconciliation-decision-service-test)
  (list "continuous-alignment-event-loop-service-contract-test" #'continuous-alignment-event-loop-service-contract-test)
  (list "continuous-alignment-event-loop-reopens-after-resolution-test" #'continuous-alignment-event-loop-reopens-after-resolution-test)
  (list "continuous-alignment-event-loop-requires-active-intent-test" #'continuous-alignment-event-loop-requires-active-intent-test)
  (list "continuous-alignment-event-loop-approval-resume-lifecycle-test" #'continuous-alignment-event-loop-approval-resume-lifecycle-test)
  (list "continuous-alignment-event-loop-multi-reopen-lifecycle-test" #'continuous-alignment-event-loop-multi-reopen-lifecycle-test)
  (list "environment-first-binding-test" #'environment-first-binding-test)
   (list "environment-runtime-history-persistence-test" #'environment-runtime-history-persistence-test)
   (list "environment-desktop-preferences-persistence-test" #'environment-desktop-preferences-persistence-test)
   (list "environment-desktop-preferences-legacy-key-normalization-test" #'environment-desktop-preferences-legacy-key-normalization-test)
   (list "trace-link-persistence-test" #'trace-link-persistence-test)
   (list "environment-image-registry-persistence-test" #'environment-image-registry-persistence-test)
   (list "environment-image-revert-test" #'environment-image-revert-test)
   (list "environment-image-load-assesses-recovery-test" #'environment-image-load-assesses-recovery-test)
   (list "load-environment-does-not-resync-on-read-test" #'load-environment-does-not-resync-on-read-test)
   (list "environment-status-uses-environment-owned-state-test" #'environment-status-uses-environment-owned-state-test)
   (list "session-tail-rebuild-after-load-test" #'session-tail-rebuild-after-load-test)
   (list "session-shell-commands-test" #'session-shell-commands-test)
   (list "session-summary-prefers-environment-summary-test" #'session-summary-prefers-environment-summary-test)
   (list "session-summary-prefers-environment-event-summary-test" #'session-summary-prefers-environment-event-summary-test)
   (list "environment-shell-commands-test" #'environment-shell-commands-test)
   (list "environment-load-shell-orientation-test" #'environment-load-shell-orientation-test)
   (list "shell-environment-orientation-render-test" #'shell-environment-orientation-render-test)
   (list "environment-load-rendering-test" #'environment-load-rendering-test)
   (list "environment-status-command-test" #'environment-status-command-test)
   (list "environment-status-blocked-work-summary-test" #'environment-status-blocked-work-summary-test)
   (list "environment-status-incident-summary-test" #'environment-status-incident-summary-test)
   (list "runtime-shell-commands-test" #'runtime-shell-commands-test)
   (list "runtime-package-switch-approval-test" #'runtime-package-switch-approval-test)
   (list "runtime-mutating-eval-approval-test" #'runtime-mutating-eval-approval-test)
   (list "runtime-reload-file-approval-and-workflow-test" #'runtime-reload-file-approval-and-workflow-test)
   (list "runtime-cold-validation-finalization-test" #'runtime-cold-validation-finalization-test)
   (list "runtime-eval-incident-recording-test" #'runtime-eval-incident-recording-test)
   (list "turn-resume-mutating-runtime-eval-turn-evidence-test" #'turn-resume-mutating-runtime-eval-turn-evidence-test)
   (list "turn-resume-runtime-reload-turn-evidence-test" #'turn-resume-runtime-reload-turn-evidence-test)
   (list "mutation-review-command-test" #'mutation-review-command-test)
   (list "mutation-review-cold-validation-test" #'mutation-review-cold-validation-test)
   (list "mutation-review-incident-linked-test" #'mutation-review-incident-linked-test)
   (list "turn-resume-runtime-incident-quarantine-test" #'turn-resume-runtime-incident-quarantine-test)
   (list "incident-workspace-runtime-context-test" #'incident-workspace-runtime-context-test)
   (list "incident-recommended-recovery-test" #'incident-recommended-recovery-test)
   (list "incident-recovery-artifact-test" #'incident-recovery-artifact-test)
   (list "incident-aware-session-and-environment-summary-test" #'incident-aware-session-and-environment-summary-test)
   (list "non-thread-validation-artifact-test" #'non-thread-validation-artifact-test)
   (list "environment-native-artifact-test" #'environment-native-artifact-test)
   (list "environment-artifact-summary-prefers-environment-state-test" #'environment-artifact-summary-prefers-environment-state-test)
   (list "provider-artifact-summary-prefers-environment-state-test" #'provider-artifact-summary-prefers-environment-state-test)
   (list "artifact-inspection-prefers-environment-state-test" #'artifact-inspection-prefers-environment-state-test)
   (list "environment-level-evidence-summary-test" #'environment-level-evidence-summary-test)
   (list "reconciliation-artifact-coverage-test" #'reconciliation-artifact-coverage-test)
   (list "turn-recovery-persists-across-session-load-test" #'turn-recovery-persists-across-session-load-test)
   (list "interrupted-turn-state-recovered-on-session-load-test" #'interrupted-turn-state-recovered-on-session-load-test)
   (list "list-tools-test" #'list-tools-test)
   (list "session-summary-tool-test" #'session-summary-tool-test)
   (list "session-summary-uses-environment-thread-state-test" #'session-summary-uses-environment-thread-state-test)
   (list "session-events-tool-test" #'session-events-tool-test)
   (list "session-events-tool-prefers-environment-event-log-test" #'session-events-tool-prefers-environment-event-log-test)
   (list "docs-read-tool-test" #'docs-read-tool-test)
   (list "docs-read-path-escape-test" #'docs-read-path-escape-test)
   (list "fs-read-tool-test" #'fs-read-tool-test)
   (list "fs-read-path-escape-test" #'fs-read-path-escape-test)
   (list "proc-run-approval-test" #'proc-run-approval-test)
   (list "approve-and-run-tool-test" #'approve-and-run-tool-test)
   (list "git-read-approval-test" #'git-read-approval-test)
   (list "git-status-and-diff-test" #'git-status-and-diff-test)
   (list "git-write-flow-test" #'git-write-flow-test)
   (list "patch-approval-and-apply-test" #'patch-approval-and-apply-test)
   (list "artifact-persistence-test" #'artifact-persistence-test)
   (list "patch-path-escape-test" #'patch-path-escape-test)))

(defun all-test-cases ()
  (append (annotate-test-cases :core-cli (core-and-cli-tests))
          (annotate-test-cases :provider-conversation (provider-and-conversation-tests))
          (annotate-test-cases :interaction-boundary (interaction-boundary-tests))
          (annotate-derived-test-cases #'extended-suite-test-category
                                       (extended-suite-tests))))

(defun all-test-categories ()
  (remove-duplicates (mapcar #'catalog-case-category (all-test-cases))
                     :test #'eq))

(defun normalize-test-category-token (token)
  (intern (string-upcase (string token)) "KEYWORD"))

(defun filter-test-cases-by-categories (categories)
  (let ((normalized (mapcar #'normalize-test-category-token categories)))
    (remove-if-not (lambda (case)
                     (member (catalog-case-category case) normalized :test #'eq))
                   (all-test-cases))))

(defun available-test-harnesses ()
  (append
   (list (list :id :full-suite
               :label "Full Lisp Suite"
               :entrypoint "./bin/run-tests"
               :kind :suite)
         (list :id :coverage
               :label "Coverage"
               :entrypoint "./bin/run-coverage"
               :kind :coverage)
         (list :id :internal-evaluations
               :label "Internal Evaluations"
               :entrypoint "./bin/run-evals"
               :kind :evaluation)
         (list :id :performance-benchmarks
               :label "Performance Benchmarks"
               :entrypoint "./bin/run-performance"
               :kind :performance))
   (focused-test-harnesses)))

(defun focused-test-harnesses ()
  (list (list :id :service-contracts
              :label "Service Contracts"
              :entrypoint "./bin/run-test-service-contracts"
              :kind :focused-suite
              :categories '(:service-contracts))
        (list :id :workflow-governance
              :label "Workflow And Governance"
              :entrypoint "./bin/run-test-workflow-governance"
              :kind :focused-suite
              :categories '(:workflow-and-governance))
        (list :id :shell-compatibility
              :label "Shell And Compatibility"
              :entrypoint "./bin/run-test-shell-compatibility"
              :kind :focused-suite
              :categories '(:shell-and-compatibility))
        (list :id :retrieval-memory
              :label "Retrieval And Memory"
              :entrypoint "./bin/run-test-retrieval-memory"
              :kind :focused-suite
              :categories '(:retrieval-and-memory))
        (list :id :environment-persistence
              :label "Environment And Persistence"
              :entrypoint "./bin/run-test-environment-persistence"
              :kind :focused-suite
              :categories '(:environment-and-persistence))))

(defun find-test-harness (harness-id)
  (find (normalize-test-category-token harness-id)
        (available-test-harnesses)
        :key (lambda (entry) (getf entry :id))
        :test #'eq))

(defun run-catalog-test-case (case)
  (let* ((name (catalog-case-name case))
         (category (catalog-case-category case))
         (thunk (catalog-case-thunk case))
         (started (get-internal-real-time)))
    (unwind-protect
         (handler-case
             (progn
               (funcall thunk)
               (let ((duration (/ (- (get-internal-real-time) started)
                                  internal-time-units-per-second)))
                 (format t "PASS [~(~A~)] ~A~%" category name)
                 (list :name name
                       :category category
                       :status :passed
                       :duration-seconds duration)))
           (error (condition)
             (let ((duration (/ (- (get-internal-real-time) started)
                                internal-time-units-per-second)))
               (format t "FAIL [~(~A~)] ~A~%" category name)
               (list :name name
                     :category category
                     :status :failed
                     :duration-seconds duration
                     :error (princ-to-string condition)))))
      (ignore-errors
        (sb-ext:gc :full t)))))

(defun summarize-test-results (results)
  (let* ((total (length results))
         (passed (count :passed results :key (lambda (entry) (getf entry :status)) :test #'eq))
         (failed (count :failed results :key (lambda (entry) (getf entry :status)) :test #'eq))
         (duration (reduce #'+ results
                           :key (lambda (entry) (or (getf entry :duration-seconds) 0.0))
                           :initial-value 0.0))
         (categories (remove-duplicates (mapcar (lambda (entry) (getf entry :category)) results)
                                        :test #'eq))
         (category-summaries
           (mapcar (lambda (category)
                     (let* ((entries (remove-if-not (lambda (entry)
                                                      (eq category (getf entry :category)))
                                                    results))
                            (entry-total (length entries))
                            (entry-passed (count :passed entries :key (lambda (entry) (getf entry :status)) :test #'eq))
                            (entry-failed (count :failed entries :key (lambda (entry) (getf entry :status)) :test #'eq))
                            (entry-duration (reduce #'+ entries
                                                    :key (lambda (entry) (or (getf entry :duration-seconds) 0.0))
                                                    :initial-value 0.0)))
                       (list :category category
                             :total entry-total
                             :passed entry-passed
                             :failed entry-failed
                             :duration-seconds entry-duration)))
                   categories)))
    (list :total total
          :passed passed
          :failed failed
          :duration-seconds duration
          :categories category-summaries)))

(defun generate-test-program-report (results)
  (list :generated-at (get-universal-time)
        :suite-id :sbcl-agent
        :summary (summarize-test-results results)
        :results results
        :harnesses (available-test-harnesses)))

(defun ensure-test-report-directory ()
  (let ((root (merge-pathnames #P"tmp/test-results/"
                               (uiop:ensure-directory-pathname
                                (uiop:getcwd)))))
    (ensure-directories-exist root)
    root))

(defun write-test-report-json (report)
  (let* ((root (ensure-test-report-directory))
         (path (merge-pathnames #P"latest-report.json" root)))
    (with-open-file (stream path
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (write-string (sbcl-agent::emit-json
                     (sbcl-agent::platform-json-safe-value report))
                    stream))
    path))

(defun write-test-report-markdown (report)
  (let* ((root (ensure-test-report-directory))
         (path (merge-pathnames #P"latest-report.md" root))
         (summary (getf report :summary)))
    (with-open-file (stream path
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (format stream "# sbcl-agent Test Program Report~%~%")
      (format stream "- Generated at: ~A~%" (getf report :generated-at))
      (format stream "- Total tests: ~D~%" (or (getf summary :total) 0))
      (format stream "- Passed: ~D~%" (or (getf summary :passed) 0))
      (format stream "- Failed: ~D~%" (or (getf summary :failed) 0))
      (format stream "- Duration seconds: ~,3F~%~%" (or (getf summary :duration-seconds) 0.0))
      (format stream "## Categories~%~%")
      (dolist (entry (or (getf summary :categories) '()))
        (format stream "- `~(~A~)`: total=~D passed=~D failed=~D duration=~,3Fs~%"
                (getf entry :category)
                (or (getf entry :total) 0)
                (or (getf entry :passed) 0)
                (or (getf entry :failed) 0)
                (or (getf entry :duration-seconds) 0.0)))
      (format stream "~%## Harnesses~%~%")
      (dolist (entry (or (getf report :harnesses) '()))
        (format stream "- `~(~A~)`: ~A via `~A`~%"
                (getf entry :id)
                (or (getf entry :label) "")
                (or (getf entry :entrypoint) "")))
      (format stream "~%## Failures~%~%")
      (let ((failures (remove :failed (getf report :results)
                              :key (lambda (entry) (getf entry :status))
                              :test-not #'eq)))
        (if failures
            (dolist (entry failures)
              (format stream "- `~A` (`~(~A~)`): ~A~%"
                      (getf entry :name)
                      (getf entry :category)
                      (or (getf entry :error) "Unknown failure")))
            (format stream "- None~%"))))
    path))

(defun run-test-program (&key stop-on-failure)
  (run-test-program-category :categories (all-test-categories)
                             :stop-on-failure stop-on-failure))

(defun run-test-program-category (&key categories stop-on-failure)
  (let ((results '()))
    (dolist (case (filter-test-cases-by-categories
                   (or categories (all-test-categories))))
      (let ((result (run-catalog-test-case case)))
        (push result results)
        (when (and stop-on-failure
                   (eq :failed (getf result :status)))
          (error "~A" (or (getf result :error)
                          (format nil "Test ~A failed" (getf result :name)))))))
    (nreverse results)))

(defun run-and-write-test-report ()
  (format t "Running sbcl-agent categorized test program...~%")
  (let* ((results (run-test-program :stop-on-failure nil))
         (report (generate-test-program-report results))
         (json-path (write-test-report-json report))
         (markdown-path (write-test-report-markdown report))
         (summary (getf report :summary)))
    (format t "test-report> total=~D passed=~D failed=~D duration=~,3Fs~%"
            (or (getf summary :total) 0)
            (or (getf summary :passed) 0)
            (or (getf summary :failed) 0)
            (or (getf summary :duration-seconds) 0.0))
    (format t "test-report/json> ~A~%" (namestring json-path))
    (format t "test-report/markdown> ~A~%" (namestring markdown-path))
    report))

(defun run-and-write-test-report-for-categories (categories)
  (format t "Running sbcl-agent focused test program for ~{~A~^, ~}...~%"
          categories)
  (let* ((results (run-test-program-category :categories categories
                                             :stop-on-failure nil))
         (report (generate-test-program-report results))
         (json-path (write-test-report-json report))
         (markdown-path (write-test-report-markdown report))
         (summary (getf report :summary)))
    (format t "test-report> total=~D passed=~D failed=~D duration=~,3Fs~%"
            (or (getf summary :total) 0)
            (or (getf summary :passed) 0)
            (or (getf summary :failed) 0)
            (or (getf summary :duration-seconds) 0.0))
    (format t "test-report/json> ~A~%" (namestring json-path))
    (format t "test-report/markdown> ~A~%" (namestring markdown-path))
    report))

(defun run-and-write-test-report-for-harness (harness-id)
  (let ((harness (find-test-harness harness-id)))
    (unless harness
      (error "Unknown test harness ~A" harness-id))
    (let ((categories (getf harness :categories)))
      (if categories
          (run-and-write-test-report-for-categories categories)
          (run-and-write-test-report)))))

(defun generate-test-evidence-index ()
  (let* ((report-root (ensure-test-report-directory))
         (latest-json (merge-pathnames #P"latest-report.json" report-root))
         (latest-markdown (merge-pathnames #P"latest-report.md" report-root))
         (coverage-index (merge-pathnames #P"tmp/coverage/cover-index.html"
                                          (uiop:ensure-directory-pathname
                                           (uiop:getcwd)))))
    (list :generated-at (get-universal-time)
          :program :sbcl-agent
          :harnesses (available-test-harnesses)
          :artifacts (list :latest-report-json (when (probe-file latest-json)
                                                 (namestring latest-json))
                           :latest-report-markdown (when (probe-file latest-markdown)
                                                     (namestring latest-markdown))
                           :coverage-index (when (probe-file coverage-index)
                                             (namestring coverage-index))))))

(defun write-test-evidence-index-json (index)
  (let* ((root (ensure-test-report-directory))
         (path (merge-pathnames #P"evidence-index.json" root)))
    (with-open-file (stream path
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (write-string (sbcl-agent::emit-json
                     (sbcl-agent::platform-json-safe-value index))
                    stream))
    path))

(defun write-test-evidence-index-markdown (index)
  (let* ((root (ensure-test-report-directory))
         (path (merge-pathnames #P"evidence-index.md" root)))
    (with-open-file (stream path
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (format stream "# sbcl-agent Test Evidence Index~%~%")
      (format stream "- Generated at: ~A~%~%" (getf index :generated-at))
      (format stream "## Harnesses~%~%")
      (dolist (entry (getf index :harnesses))
        (format stream "- `~(~A~)`: ~A via `~A`~%"
                (getf entry :id)
                (or (getf entry :label) "")
                (or (getf entry :entrypoint) ""))
        (let ((categories (getf entry :categories)))
          (when categories
            (format stream "  categories: ~{`~(~A~)`~^, ~}~%"
                    categories))))
      (format stream "~%## Artifacts~%~%")
      (dolist (artifact '(:latest-report-json :latest-report-markdown :coverage-index))
        (format stream "- `~(~A~)`: ~A~%"
                artifact
                (or (getf (getf index :artifacts) artifact) "not generated"))))
    path))

(defun write-test-evidence-index ()
  (let* ((index (generate-test-evidence-index))
         (json-path (write-test-evidence-index-json index))
         (markdown-path (write-test-evidence-index-markdown index)))
    (format t "test-evidence/json> ~A~%" (namestring json-path))
    (format t "test-evidence/markdown> ~A~%" (namestring markdown-path))
    index))

(defun run-all-tests ()
  (format t "Running sbcl-agent test suite...~%")
  (run-test-program :stop-on-failure t)
  (format t "All tests passed.~%")
  t)
