(in-package #:sbcl-agent.calculator)

(defparameter +calculator-modes+ '(:basic :scientific :programmer))
(defparameter +calculator-bases+ '(2 8 10 16))
(defparameter +calculator-word-sizes+ '(8 16 32 64))
(defparameter +calculator-angle-units+ '(:radians :degrees))

(defun normalize-mode (value)
  (let ((mode (etypecase value
                (keyword value)
                (string (intern (string-upcase value) "KEYWORD")))))
    (unless (member mode +calculator-modes+)
      (error "Unsupported calculator mode ~S" value))
    mode))

(defun normalize-base (value)
  (let ((base (etypecase value
                (integer value)
                (string (parse-integer value))
                (keyword (parse-integer (symbol-name value))))))
    (unless (member base +calculator-bases+)
      (error "Unsupported calculator base ~S" value))
    base))

(defun normalize-word-size (value)
  (let ((word-size (etypecase value
                     (integer value)
                     (string (parse-integer value))
                     (keyword (parse-integer (symbol-name value))))))
    (unless (member word-size +calculator-word-sizes+)
      (error "Unsupported calculator word size ~S" value))
    word-size))

(defun normalize-angle-unit (value)
  (let ((unit (etypecase value
                (keyword value)
                (string (intern (string-upcase value) "KEYWORD")))))
    (unless (member unit +calculator-angle-units+)
      (error "Unsupported calculator angle unit ~S" value))
    unit))

(defun calculator-summary ()
  (list :available-modes +calculator-modes+
        :default-mode :basic
        :available-bases +calculator-bases+
        :default-base 10
        :available-word-sizes +calculator-word-sizes+
        :default-word-size 64
        :available-angle-units +calculator-angle-units+
        :default-angle-unit :radians
        :summary "Evaluate calculator expressions in basic, scientific, and programmer modes."))

(defun whitespace-char-p (character)
  (find character '(#\Space #\Tab #\Newline #\Return)))

(defun identifier-start-char-p (character)
  (or (alpha-char-p character)
      (char= character #\_)))

(defun identifier-char-p (character)
  (or (identifier-start-char-p character)
      (digit-char-p character)
      (char= character #\-)))

(defun tokenize-expression (expression)
  (let ((length (length expression))
        (tokens '())
        (index 0))
    (labels ((peek (&optional (offset 0))
               (and (< (+ index offset) length)
                    (char expression (+ index offset))))
             (consume-token (start end)
               (let ((token (subseq expression start end)))
                 (push token tokens)
                 (setf index end))))
      (loop while (< index length)
            for character = (peek)
            do (cond
                 ((or (null character) (whitespace-char-p character))
                  (incf index))
                 ((and (char= character #\<)
                       (char= (or (peek 1) #\Space) #\<))
                  (consume-token index (+ index 2)))
                 ((and (char= character #\>)
                       (char= (or (peek 1) #\Space) #\>))
                  (consume-token index (+ index 2)))
                 ((find character '(#\( #\) #\, #\+ #\- #\* #\/ #\% #\^ #\! #\~ #\& #\|))
                  (consume-token index (+ index 1)))
                 ((or (digit-char-p character)
                      (and (char= character #\.)
                           (digit-char-p (or (peek 1) #\Space))))
                  (let ((start index))
                    (incf index)
                    (if (and (char= character #\0)
                             (< index length)
                             (find (char-downcase (peek)) '(#\x #\o #\b)))
                        (progn
                          (incf index)
                          (loop while (and (< index length)
                                           (or (digit-char-p (peek))
                                               (find (char-upcase (peek)) "ABCDEF")))
                                do (incf index)))
                        (loop while (and (< index length)
                                         (or (digit-char-p (peek))
                                             (char= (peek) #\.)
                                             (find (char-downcase (peek)) '(#\e #\d #\f #\l #\s #\+ #\-))))
                              do (cond
                                   ((and (find (char-downcase (peek)) '(#\+ #\-))
                                         (> index start)
                                         (not (find (char-downcase (char expression (1- index))) '(#\e #\d #\f #\l #\s))))
                                    (return))
                                   (t
                                    (incf index)))))
                    (push (subseq expression start index) tokens)))
                 ((identifier-start-char-p character)
                  (let ((start index))
                    (incf index)
                    (loop while (and (< index length)
                                     (identifier-char-p (peek)))
                          do (incf index))
                    (push (subseq expression start index) tokens)))
                 (t
                  (error "Unsupported calculator token starting at ~S" (subseq expression index (min length (+ index 8))))))))
    (nreverse tokens)))

(defun make-calculator-context (&key (mode :basic) (base 10) (word-size 64) (angle-unit :radians))
  (list :mode (normalize-mode mode)
        :base (normalize-base base)
        :word-size (normalize-word-size word-size)
        :angle-unit (normalize-angle-unit angle-unit)))

(defun programmer-mode-p (context)
  (eq (getf context :mode) :programmer))

(defun scientific-mode-p (context)
  (eq (getf context :mode) :scientific))

(defun angle->radians (value context)
  (if (eq (getf context :angle-unit) :degrees)
      (* value (/ pi 180d0))
      value))

(defun radians->angle (value context)
  (if (eq (getf context :angle-unit) :degrees)
      (* value (/ 180d0 pi))
      value))

(defun ensure-calculator-integer (value operation)
  (unless (integerp value)
    (error "~A requires an integer value." operation))
  value)

(defun ensure-nonnegative-integer (value operation)
  (let ((integer (ensure-calculator-integer value operation)))
    (when (minusp integer)
      (error "~A requires a non-negative integer." operation))
    integer))

(defun word-size-mask (context)
  (1- (ash 1 (getf context :word-size))))

(defun normalize-programmer-value (value context)
  (let* ((mask (word-size-mask context))
         (unsigned (logand mask (ensure-calculator-integer value "Programmer mode"))))
    (if (logbitp (1- (getf context :word-size)) unsigned)
        (- unsigned (ash 1 (getf context :word-size)))
        unsigned)))

(defun unsigned-programmer-value (value context)
  (logand (word-size-mask context) (ensure-calculator-integer value "Programmer mode")))

(defun coerce-calculator-result (value context)
  (if (programmer-mode-p context)
      (normalize-programmer-value value context)
      value))

(defun parse-basic-number (token)
  (handler-case
      (let ((value (read-from-string token)))
        (unless (numberp value)
          (error "not-a-number"))
        (if (typep value 'rational)
            (coerce value 'double-float)
            value))
    (error ()
      (error "Unable to parse calculator number ~S." token))))

(defun prefixed-programmer-base (token)
  (cond
    ((and (> (length token) 2)
          (string-equal token "0x" :end1 2 :end2 2))
     16)
    ((and (> (length token) 2)
          (string-equal token "0b" :end1 2 :end2 2))
     2)
    ((and (> (length token) 2)
          (string-equal token "0o" :end1 2 :end2 2))
     8)
    (t nil)))

(defun parse-programmer-number (token context)
  (let* ((prefix-base (prefixed-programmer-base token))
         (base (or prefix-base (getf context :base)))
         (digits (if prefix-base (subseq token 2) token)))
    (when (search "." digits)
      (error "Programmer mode accepts only integers."))
    (normalize-programmer-value (parse-integer digits :radix base) context)))

(defun factorial-value (value)
  (loop for i from 1 to (ensure-nonnegative-integer value "Factorial")
        for acc = 1 then (* acc i)
        finally (return acc)))

(defun calculator-constant-value (token)
  (cond
    ((string-equal token "pi") pi)
    ((string-equal token "e") (exp 1d0))
    (t nil)))

(defun scientific-function-value (name arguments context)
  (flet ((one-arg ()
           (unless (= (length arguments) 1)
             (error "Function ~A expects exactly one argument." name))
           (first arguments))
         (two-args ()
           (unless (= (length arguments) 2)
             (error "Function ~A expects exactly two arguments." name))
           arguments))
    (cond
      ((string-equal name "sin")
       (sin (angle->radians (one-arg) context)))
      ((string-equal name "cos")
       (cos (angle->radians (one-arg) context)))
      ((string-equal name "tan")
       (tan (angle->radians (one-arg) context)))
      ((string-equal name "asin")
       (radians->angle (asin (one-arg)) context))
      ((string-equal name "acos")
       (radians->angle (acos (one-arg)) context))
      ((string-equal name "atan")
       (radians->angle (atan (one-arg)) context))
      ((string-equal name "sqrt")
       (sqrt (one-arg)))
      ((string-equal name "cbrt")
       (expt (one-arg) (/ 1d0 3d0)))
      ((string-equal name "ln")
       (log (one-arg)))
      ((or (string-equal name "log")
           (string-equal name "log10"))
       (log (one-arg) 10d0))
      ((string-equal name "exp")
       (exp (one-arg)))
      ((string-equal name "abs")
       (abs (one-arg)))
      ((string-equal name "floor")
       (nth-value 0 (floor (one-arg))))
      ((string-equal name "ceil")
       (ceiling (one-arg)))
      ((string-equal name "round")
       (round (one-arg)))
      ((or (string-equal name "trunc")
           (string-equal name "truncate"))
       (truncate (one-arg)))
      ((or (string-equal name "fact")
           (string-equal name "factorial"))
       (factorial-value (one-arg)))
      ((string-equal name "pow")
       (destructuring-bind (left right) (two-args)
         (expt left right)))
      ((string-equal name "mod")
       (destructuring-bind (left right) (two-args)
         (mod left right)))
      ((string-equal name "shl")
       (destructuring-bind (left right) (two-args)
         (normalize-programmer-value (ash (ensure-calculator-integer left "shl")
                                          (ensure-calculator-integer right "shl"))
                                     context)))
      ((string-equal name "shr")
       (destructuring-bind (left right) (two-args)
         (normalize-programmer-value (ash (ensure-calculator-integer left "shr")
                                          (- (ensure-calculator-integer right "shr")))
                                     context)))
      ((string-equal name "not")
       (normalize-programmer-value (lognot (ensure-calculator-integer (one-arg) "not")) context))
      (t
       (error "Unknown calculator function ~S." name)))))

(defun programmer-digit-token-p (token context)
  (and (programmer-mode-p context)
       (> (length token) 0)
       (every (lambda (character)
                (digit-char-p character (getf context :base)))
              token)))

(defun parse-token-value (token context)
  (let ((constant (calculator-constant-value token)))
    (cond
      (constant constant)
      ((programmer-digit-token-p token context)
       (parse-programmer-number token context))
      ((programmer-mode-p context)
       (parse-programmer-number token context))
      (t
       (parse-basic-number token)))))

(defun evaluate-expression (expression &key (mode :basic) (base 10) (word-size 64) (angle-unit :radians))
  (let* ((trimmed (string-trim '(#\Space #\Tab #\Newline #\Return) expression))
         (context (make-calculator-context :mode mode
                                           :base base
                                           :word-size word-size
                                           :angle-unit angle-unit))
         (tokens (tokenize-expression trimmed)))
    (when (string= trimmed "")
      (error "Calculator expression cannot be empty."))
    (labels
        ((token-at (position)
           (nth position tokens))
         (parse-primary (position)
           (let ((token (token-at position)))
             (cond
               ((null token)
                (error "Unexpected end of calculator expression."))
               ((string= token "(")
                (multiple-value-bind (value next-position) (parse-bitwise-or (1+ position))
                  (unless (string= (or (token-at next-position) "") ")")
                    (error "Missing closing parenthesis in calculator expression."))
                  (values value (1+ next-position))))
               ((and (identifier-start-char-p (char token 0))
                     (string= (or (token-at (1+ position)) "") "("))
                (multiple-value-bind (arguments next-position)
                    (parse-argument-list (+ position 2))
                  (values (coerce-calculator-result
                           (scientific-function-value token arguments context)
                           context)
                          next-position)))
               ((identifier-start-char-p (char token 0))
                (values (parse-token-value token context) (1+ position)))
               (t
                (values (parse-token-value token context) (1+ position))))))
         (parse-argument-list (position)
           (if (string= (or (token-at position) "") ")")
               (values '() (1+ position))
               (loop with arguments = '()
                     with current-position = position
                     do (multiple-value-bind (value next-position) (parse-bitwise-or current-position)
                          (push value arguments)
                          (let ((separator (token-at next-position)))
                            (cond
                              ((string= separator ",")
                               (setf current-position (1+ next-position)))
                              ((string= separator ")")
                               (return (values (nreverse arguments) (1+ next-position))))
                              (t
                               (error "Malformed calculator argument list."))))))))
         (parse-postfix (position)
           (multiple-value-bind (value next-position) (parse-primary position)
             (loop while (string= (or (token-at next-position) "") "!")
                   do (setf value (coerce-calculator-result (factorial-value value) context)
                            next-position (1+ next-position)))
             (values value next-position)))
         (parse-unary (position)
           (let ((token (token-at position)))
             (cond
               ((string= token "+")
                (parse-unary (1+ position)))
               ((string= token "-")
                (multiple-value-bind (value next-position) (parse-unary (1+ position))
                  (values (coerce-calculator-result (- value) context) next-position)))
               ((or (string= token "~")
                    (string-equal token "not"))
                (multiple-value-bind (value next-position) (parse-unary (1+ position))
                  (values (normalize-programmer-value (lognot (ensure-calculator-integer value "not")) context)
                          next-position)))
               (t
                (parse-postfix position)))))
         (parse-power (position)
           (multiple-value-bind (left next-position) (parse-unary position)
             (if (string= (or (token-at next-position) "") "^")
                 (multiple-value-bind (right final-position) (parse-power (1+ next-position))
                   (values (coerce-calculator-result (expt left right) context) final-position))
                 (values left next-position))))
         (parse-multiplicative (position)
           (multiple-value-bind (left next-position) (parse-power position)
             (loop with value = left
                   with cursor = next-position
                   for token = (token-at cursor)
                   while (member token '("*" "/" "%" "mod") :test #'string-equal)
                   do (multiple-value-bind (right final-position) (parse-power (1+ cursor))
                        (setf value
                              (coerce-calculator-result
                               (cond
                                 ((string= token "*") (* value right))
                                 ((string= token "/")
                                  (if (programmer-mode-p context)
                                      (truncate value right)
                                      (/ value right)))
                                 (t
                                  (mod (ensure-calculator-integer value token)
                                       (ensure-calculator-integer right token))))
                               context)
                              cursor final-position))
                   finally (return (values value cursor)))))
         (parse-additive (position)
           (multiple-value-bind (left next-position) (parse-multiplicative position)
             (loop with value = left
                   with cursor = next-position
                   for token = (token-at cursor)
                   while (member token '("+" "-") :test #'string=)
                   do (multiple-value-bind (right final-position) (parse-multiplicative (1+ cursor))
                        (setf value (coerce-calculator-result
                                     (if (string= token "+")
                                         (+ value right)
                                         (- value right))
                                     context)
                              cursor final-position))
                   finally (return (values value cursor)))))
         (parse-shift (position)
           (multiple-value-bind (left next-position) (parse-additive position)
             (loop with value = left
                   with cursor = next-position
                   for token = (token-at cursor)
                   while (member token '("<<" ">>") :test #'string=)
                   do (multiple-value-bind (right final-position) (parse-additive (1+ cursor))
                        (let ((count (ensure-calculator-integer right token)))
                          (setf value
                                (normalize-programmer-value
                                 (ash (ensure-calculator-integer value token)
                                      (if (string= token "<<") count (- count)))
                                 context)
                                cursor final-position)))
                   finally (return (values value cursor)))))
         (parse-bitwise-and (position)
           (multiple-value-bind (left next-position) (parse-shift position)
             (loop with value = left
                   with cursor = next-position
                   for token = (token-at cursor)
                   while (string= token "&")
                   do (multiple-value-bind (right final-position) (parse-shift (1+ cursor))
                        (setf value (normalize-programmer-value
                                     (logand (ensure-calculator-integer value "&")
                                             (ensure-calculator-integer right "&"))
                                     context)
                              cursor final-position))
                   finally (return (values value cursor)))))
         (parse-bitwise-xor (position)
           (multiple-value-bind (left next-position) (parse-bitwise-and position)
             (loop with value = left
                   with cursor = next-position
                   for token = (token-at cursor)
                   while (string-equal token "xor")
                   do (multiple-value-bind (right final-position) (parse-bitwise-and (1+ cursor))
                        (setf value (normalize-programmer-value
                                     (logxor (ensure-calculator-integer value "xor")
                                             (ensure-calculator-integer right "xor"))
                                     context)
                              cursor final-position))
                   finally (return (values value cursor)))))
         (parse-bitwise-or (position)
           (multiple-value-bind (left next-position) (parse-bitwise-xor position)
             (loop with value = left
                   with cursor = next-position
                   for token = (token-at cursor)
                   while (or (string= token "|") (string-equal token "or"))
                   do (multiple-value-bind (right final-position) (parse-bitwise-xor (1+ cursor))
                        (setf value (normalize-programmer-value
                                     (logior (ensure-calculator-integer value "or")
                                             (ensure-calculator-integer right "or"))
                                     context)
                              cursor final-position))
                   finally (return (values value cursor))))))
      (multiple-value-bind (value position) (parse-bitwise-or 0)
        (when (< position (length tokens))
          (error "Unexpected calculator token ~S." (token-at position)))
        (let* ((display-value (if (and (realp value) (not (integerp value)))
                                  (format nil "~,12G" (coerce value 'double-float))
                                  (princ-to-string value)))
               (integer-value (and (integerp value) value))
               (unsigned-value (and integer-value (unsigned-programmer-value integer-value context))))
          (list :mode (getf context :mode)
                :expression trimmed
                :display-value display-value
                :scientific-notation (if (realp value)
                                         (format nil "~,12E" (coerce value 'double-float))
                                         display-value)
                :base (getf context :base)
                :word-size (getf context :word-size)
                :angle-unit (getf context :angle-unit)
                :integer-result-p (not (null integer-value))
                :decimal-value (if integer-value
                                   (princ-to-string integer-value)
                                   display-value)
                :unsigned-decimal-value (and unsigned-value (princ-to-string unsigned-value))
                :hexadecimal-value (and unsigned-value (format nil "0x~X" unsigned-value))
                :octal-value (and unsigned-value (format nil "0o~O" unsigned-value))
                :binary-value (and unsigned-value (format nil "0b~B" unsigned-value))
                :summary (format nil "~A mode evaluated ~S." (string-capitalize (string-downcase (symbol-name (getf context :mode)))) trimmed)))))))
