(in-package #:sbcl-agent)

(defstruct command
  kind
  form
  arguments)

(defun command-operator-symbol (form)
  (and (consp form)
       (symbolp (first form))
       (string-downcase (symbol-name (first form)))))

(defun normalize-form-command (form)
  (let ((operator (command-operator-symbol form)))
    (cond
      ((typep form 'assistant-action)
       (make-command :kind :assistant-action :form form :arguments (list form)))
      ((or (null operator)
           (not (member operator '("ask" "say" "plan" "tool" "help" "approve" "patch" "execute-actions"
                                   "provider/show" "provider/list" "provider/use" "provider/configure" "provider/routing" "provider/route"
                                   "platform/manifest" "platform/package" "platform/show-package" "platform/validate-package" "platform/import-package" "platform/list-packages" "platform/show-imported-package" "platform/activate-package" "platform/deactivate-package" "platform/active-packages" "platform/profile" "platform/install-package"
                                   "execution/show" "execution/control" "compatibility/list" "compatibility/show"
                                   "workspace/show" "desktop/show" "desktop/panel" "desktop/select" "desktop/restore" "desktop/action" "surface/list" "surface/select" "surface/step" "open" "focus/show" "focus/set" "governance/queue" "governance/select" "object-browser" "object-browser/select" "inspector/show"
                                   "thread/new" "thread/list" "thread/use" "thread/show" "turn/status" "turn/resume" "incident/list" "incident/show"
                                   "environment/status" "review/mutation"
                                   "integration/rgp-bind" "integration/rgp-show" "integration/rgp-workspace" "integration/rgp-export" "integration/rgp-artifacts" "integration/rgp-approvals" "integration/rgp-approve" "integration/rgp-resume"
                                   "runtime/current-package" "runtime/list-loaded-systems" "runtime/describe-symbol" "runtime/find-definition" "runtime/callers" "runtime/methods" "runtime/source-image-divergence" "runtime/set-package" "runtime/eval" "runtime/history" "runtime/reload-file"
                                   "environment/show" "environment/events" "environment/save" "environment/load"
                                   "session/save" "session/load" "session/reset" "describe-session"
                                   "enqueue-task" "list-tasks" "describe-task" "cancel-task"
                                   "run-next-task" "start-worker" "stop-worker"
                                   "list-workers" "describe-worker" "monitor-task" "list-work-items" "describe-work-item" "describe-work-item-plan" "list-workflow-records" "describe-workflow-record" "request-work-item-approval" "quarantine-work-item" "resume-work-item" "steer-work-item-plan" "why-waiting" "list-replay-groups" "list-image-reconciliations" "replay-validator-task" "replay-validator-set" "reconcile-image-only-source")
                        :test #'string=)))
       (make-command :kind :eval :form form :arguments (list form)))
      ((string= operator "ask")
       (make-command :kind :ask :form form :arguments (rest form)))
      ((string= operator "say")
       (make-command :kind :say :form form :arguments (rest form)))
      ((string= operator "plan")
       (make-command :kind :plan :form form :arguments (rest form)))
      ((string= operator "tool")
       (make-command :kind :tool :form form :arguments (rest form)))
      ((string= operator "help")
       (make-command :kind :help :form form :arguments (rest form)))
      ((string= operator "approve")
       (make-command :kind :approve :form form :arguments (rest form)))
      ((string= operator "patch")
       (make-command :kind :patch :form form :arguments (rest form)))
      ((string= operator "execute-actions")
       (make-command :kind :execute-actions :form form :arguments (rest form)))
      ((string= operator "provider/show")
       (make-command :kind :provider-show :form form :arguments (rest form)))
      ((string= operator "provider/list")
       (make-command :kind :provider-list :form form :arguments (rest form)))
      ((string= operator "provider/use")
       (make-command :kind :provider-use :form form :arguments (rest form)))
      ((string= operator "provider/configure")
       (make-command :kind :provider-configure :form form :arguments (rest form)))
      ((string= operator "provider/routing")
       (make-command :kind :provider-routing :form form :arguments (rest form)))
      ((string= operator "provider/route")
       (make-command :kind :provider-route :form form :arguments (rest form)))
      ((string= operator "platform/manifest")
       (make-command :kind :platform-manifest :form form :arguments (rest form)))
      ((string= operator "platform/package")
       (make-command :kind :platform-package :form form :arguments (rest form)))
      ((string= operator "platform/show-package")
       (make-command :kind :platform-show-package :form form :arguments (rest form)))
      ((string= operator "platform/validate-package")
       (make-command :kind :platform-validate-package :form form :arguments (rest form)))
      ((string= operator "platform/import-package")
       (make-command :kind :platform-import-package :form form :arguments (rest form)))
      ((string= operator "platform/list-packages")
       (make-command :kind :platform-list-packages :form form :arguments (rest form)))
      ((string= operator "platform/show-imported-package")
       (make-command :kind :platform-show-imported-package :form form :arguments (rest form)))
      ((string= operator "platform/activate-package")
       (make-command :kind :platform-activate-package :form form :arguments (rest form)))
      ((string= operator "platform/deactivate-package")
       (make-command :kind :platform-deactivate-package :form form :arguments (rest form)))
      ((string= operator "platform/active-packages")
       (make-command :kind :platform-active-packages :form form :arguments (rest form)))
      ((string= operator "platform/profile")
       (make-command :kind :platform-profile :form form :arguments (rest form)))
      ((string= operator "platform/install-package")
       (make-command :kind :platform-install-package :form form :arguments (rest form)))
      ((string= operator "execution/show")
       (make-command :kind :execution-show :form form :arguments (rest form)))
      ((string= operator "execution/control")
       (make-command :kind :execution-control :form form :arguments (rest form)))
      ((string= operator "compatibility/list")
       (make-command :kind :compatibility-list :form form :arguments (rest form)))
      ((string= operator "compatibility/show")
       (make-command :kind :compatibility-show :form form :arguments (rest form)))
      ((string= operator "workspace/show")
       (make-command :kind :workspace-show :form form :arguments (rest form)))
      ((string= operator "desktop/show")
       (make-command :kind :desktop-show :form form :arguments (rest form)))
      ((string= operator "desktop/panel")
       (make-command :kind :desktop-panel :form form :arguments (rest form)))
      ((string= operator "desktop/select")
       (make-command :kind :desktop-select :form form :arguments (rest form)))
      ((string= operator "desktop/restore")
       (make-command :kind :desktop-restore :form form :arguments (rest form)))
      ((string= operator "desktop/action")
       (make-command :kind :desktop-action :form form :arguments (rest form)))
      ((string= operator "surface/list")
       (make-command :kind :surface-list :form form :arguments (rest form)))
      ((string= operator "surface/select")
       (make-command :kind :surface-select :form form :arguments (rest form)))
      ((string= operator "surface/step")
       (make-command :kind :surface-step :form form :arguments (rest form)))
      ((string= operator "open")
       (make-command :kind :open :form form :arguments (rest form)))
      ((string= operator "focus/show")
       (make-command :kind :focus-show :form form :arguments (rest form)))
      ((string= operator "focus/set")
       (make-command :kind :focus-set :form form :arguments (rest form)))
      ((string= operator "governance/queue")
       (make-command :kind :governance-queue :form form :arguments (rest form)))
      ((string= operator "governance/select")
       (make-command :kind :governance-select :form form :arguments (rest form)))
      ((string= operator "object-browser")
       (make-command :kind :object-browser :form form :arguments (rest form)))
      ((string= operator "object-browser/select")
       (make-command :kind :object-browser-select :form form :arguments (rest form)))
      ((string= operator "inspector/show")
       (make-command :kind :inspector-show :form form :arguments (rest form)))
      ((string= operator "thread/new")
       (make-command :kind :thread-new :form form :arguments (rest form)))
      ((string= operator "thread/list")
       (make-command :kind :thread-list :form form :arguments (rest form)))
      ((string= operator "thread/use")
       (make-command :kind :thread-use :form form :arguments (rest form)))
      ((string= operator "thread/show")
       (make-command :kind :thread-show :form form :arguments (rest form)))
      ((string= operator "turn/status")
       (make-command :kind :turn-status :form form :arguments (rest form)))
      ((string= operator "turn/resume")
       (make-command :kind :turn-resume :form form :arguments (rest form)))
      ((string= operator "incident/list")
       (make-command :kind :incident-list :form form :arguments (rest form)))
      ((string= operator "incident/show")
       (make-command :kind :incident-show :form form :arguments (rest form)))
      ((string= operator "environment/status")
       (make-command :kind :environment-status :form form :arguments (rest form)))
      ((string= operator "review/mutation")
       (make-command :kind :review-mutation :form form :arguments (rest form)))
      ((string= operator "integration/rgp-bind")
       (make-command :kind :integration-rgp-bind :form form :arguments (rest form)))
      ((string= operator "integration/rgp-show")
       (make-command :kind :integration-rgp-show :form form :arguments (rest form)))
      ((string= operator "integration/rgp-workspace")
       (make-command :kind :integration-rgp-workspace :form form :arguments (rest form)))
      ((string= operator "integration/rgp-export")
       (make-command :kind :integration-rgp-export :form form :arguments (rest form)))
      ((string= operator "integration/rgp-artifacts")
       (make-command :kind :integration-rgp-artifacts :form form :arguments (rest form)))
      ((string= operator "integration/rgp-approvals")
       (make-command :kind :integration-rgp-approvals :form form :arguments (rest form)))
      ((string= operator "integration/rgp-approve")
       (make-command :kind :integration-rgp-approve :form form :arguments (rest form)))
      ((string= operator "integration/rgp-resume")
       (make-command :kind :integration-rgp-resume :form form :arguments (rest form)))
      ((string= operator "runtime/current-package")
       (make-command :kind :runtime-current-package :form form :arguments (rest form)))
      ((string= operator "runtime/list-loaded-systems")
       (make-command :kind :runtime-list-loaded-systems :form form :arguments (rest form)))
      ((string= operator "runtime/describe-symbol")
       (make-command :kind :runtime-describe-symbol :form form :arguments (rest form)))
      ((string= operator "runtime/find-definition")
       (make-command :kind :runtime-find-definition :form form :arguments (rest form)))
      ((string= operator "runtime/callers")
       (make-command :kind :runtime-callers :form form :arguments (rest form)))
      ((string= operator "runtime/methods")
       (make-command :kind :runtime-methods :form form :arguments (rest form)))
      ((string= operator "runtime/source-image-divergence")
       (make-command :kind :runtime-source-image-divergence :form form :arguments (rest form)))
      ((string= operator "runtime/set-package")
       (make-command :kind :runtime-set-package :form form :arguments (rest form)))
      ((string= operator "runtime/eval")
       (make-command :kind :runtime-eval :form form :arguments (rest form)))
      ((string= operator "runtime/history")
       (make-command :kind :runtime-history :form form :arguments (rest form)))
      ((string= operator "runtime/reload-file")
       (make-command :kind :runtime-reload-file :form form :arguments (rest form)))
      ((string= operator "environment/show")
       (make-command :kind :environment-show :form form :arguments (rest form)))
      ((string= operator "environment/events")
       (make-command :kind :environment-events :form form :arguments (rest form)))
      ((string= operator "environment/save")
       (make-command :kind :environment-save :form form :arguments (rest form)))
      ((string= operator "environment/load")
       (make-command :kind :environment-load :form form :arguments (rest form)))
      ((string= operator "session/save")
       (make-command :kind :session-save :form form :arguments (rest form)))
      ((string= operator "session/load")
       (make-command :kind :session-load :form form :arguments (rest form)))
      ((string= operator "session/reset")
       (make-command :kind :session-reset :form form :arguments (rest form)))
      ((string= operator "describe-session")
       (make-command :kind :describe-session :form form :arguments (rest form)))
      ((string= operator "enqueue-task")
       (make-command :kind :enqueue-task :form form :arguments (rest form)))
      ((string= operator "list-tasks")
       (make-command :kind :list-tasks :form form :arguments (rest form)))
      ((string= operator "describe-task")
       (make-command :kind :describe-task :form form :arguments (rest form)))
      ((string= operator "cancel-task")
       (make-command :kind :cancel-task :form form :arguments (rest form)))
      ((string= operator "run-next-task")
       (make-command :kind :run-next-task :form form :arguments (rest form)))
      ((string= operator "start-worker")
       (make-command :kind :start-worker :form form :arguments (rest form)))
      ((string= operator "stop-worker")
       (make-command :kind :stop-worker :form form :arguments (rest form)))
      ((string= operator "list-workers")
       (make-command :kind :list-workers :form form :arguments (rest form)))
      ((string= operator "describe-worker")
       (make-command :kind :describe-worker :form form :arguments (rest form)))
      ((string= operator "monitor-task")
       (make-command :kind :monitor-task :form form :arguments (rest form)))
      ((string= operator "list-work-items")
       (make-command :kind :list-work-items :form form :arguments (rest form)))
      ((string= operator "describe-work-item")
       (make-command :kind :describe-work-item :form form :arguments (rest form)))
      ((string= operator "describe-work-item-plan")
       (make-command :kind :describe-work-item-plan :form form :arguments (rest form)))
      ((string= operator "list-workflow-records")
       (make-command :kind :list-workflow-records :form form :arguments (rest form)))
      ((string= operator "describe-workflow-record")
       (make-command :kind :describe-workflow-record :form form :arguments (rest form)))
      ((string= operator "request-work-item-approval")
       (make-command :kind :request-work-item-approval :form form :arguments (rest form)))
      ((string= operator "quarantine-work-item")
       (make-command :kind :quarantine-work-item :form form :arguments (rest form)))
      ((string= operator "resume-work-item")
       (make-command :kind :resume-work-item :form form :arguments (rest form)))
      ((string= operator "steer-work-item-plan")
       (make-command :kind :steer-work-item-plan :form form :arguments (rest form)))
      ((string= operator "why-waiting")
       (make-command :kind :why-waiting :form form :arguments (rest form)))
      ((string= operator "list-replay-groups")
       (make-command :kind :list-replay-groups :form form :arguments (rest form)))
      ((string= operator "list-image-reconciliations")
       (make-command :kind :list-image-reconciliations :form form :arguments (rest form)))
      ((string= operator "replay-validator-task")
       (make-command :kind :replay-validator-task :form form :arguments (rest form)))
      ((string= operator "replay-validator-set")
       (make-command :kind :replay-validator-set :form form :arguments (rest form)))
      ((string= operator "reconcile-image-only-source")
       (make-command :kind :reconcile-image-only-source :form form :arguments (rest form)))
      (t
       (make-command :kind :eval :form form :arguments (list form))))))

(defun command-summary (command)
  (list :kind (command-kind command)
        :form (command-form command)
        :arguments (command-arguments command)))
