(in-package #:sbcl-agent)

(defstruct environment-compatibility-payload
  session-id)

(defun environment-event->session-event (environment-event)
  (let ((environment-metadata (event-metadata environment-event)))
    (make-event :id (or (getf environment-metadata :source-event-id)
                        (event-id environment-event))
                :timestamp (event-timestamp environment-event)
                :kind (event-kind environment-event)
                :family (event-family environment-event)
                :entity-id (event-entity-id environment-event)
                :thread-id (event-thread-id environment-event)
                :turn-id (event-turn-id environment-event)
                :visibility (event-visibility environment-event)
                :metadata (event-metadata environment-event)
                :payload (or (getf (event-payload environment-event) :event)
                             (getf (event-payload environment-event) :event-summary)
                             (event-payload environment-event)))))

(defun conversation-summary->thread (summary)
  (make-thread :id (getf summary :id)
               :title (getf summary :title)
               :created-at (getf summary :created-at)
               :updated-at (getf summary :updated-at)
               :summary (getf summary :summary)
               :message-ids '()
               :message-ids-tail nil
               :turn-ids '()
               :turn-ids-tail nil
               :artifact-ids '()
               :artifact-ids-tail nil
               :status (getf summary :status)
               :metadata (getf summary :metadata)))

(defun conversation-summary->message (summary)
  (make-message :id (getf summary :id)
                :thread-id (getf summary :thread-id)
                :role (getf summary :role)
                :content (getf summary :content)
                :content-type (getf summary :content-type)
                :created-at (getf summary :created-at)
                :turn-id (getf summary :turn-id)
                :stream-fragments '()
                :finalized-p (getf summary :finalized-p)
                :metadata (getf summary :metadata)))

(defun conversation-summary->turn (summary)
  (make-turn :id (getf summary :id)
             :thread-id (getf summary :thread-id)
             :user-message-id (getf summary :user-message-id)
             :assistant-message-id (getf summary :assistant-message-id)
             :status (getf summary :status)
             :started-at (getf summary :started-at)
             :completed-at (getf summary :completed-at)
             :operation-ids '()
             :operation-ids-tail nil
             :artifact-ids '()
             :artifact-ids-tail nil
             :error-state (getf summary :error-state)
             :metadata (getf summary :metadata)))

(defun conversation-summary->operation (summary)
  (make-operation :id (getf summary :id)
                  :thread-id (getf summary :thread-id)
                  :turn-id (getf summary :turn-id)
                  :kind (getf summary :kind)
                  :name (getf summary :name)
                  :input (getf summary :input)
                  :policy-decision (getf summary :policy-decision)
                  :status (getf summary :status)
                  :output (getf summary :output)
                  :started-at (getf summary :started-at)
                  :completed-at (getf summary :completed-at)
                  :metadata (getf summary :metadata)))

(defun conversation-summary->artifact (summary)
  (make-artifact :id (getf summary :id)
                 :kind (getf summary :kind)
                 :path (getf summary :path)
                 :title (getf summary :title)
                 :summary (getf summary :summary)
                 :thread-id (getf summary :thread-id)
                 :turn-id (getf summary :turn-id)
                 :operation-id (getf summary :operation-id)
                 :work-item-id (getf summary :work-item-id)
                 :source-ref (getf summary :source-ref)
                 :image-ref (getf summary :image-ref)
                 :created-at (getf summary :created-at)
                 :metadata (getf summary :metadata)))

(defun rehydrate-session-conversation-from-environment (session environment)
  (let* ((conversation-state (environment-conversation-state environment))
         (thread-summaries (and conversation-state
                                (environment-conversation-state-threads conversation-state)))
         (message-summaries (and conversation-state
                                 (environment-conversation-state-messages conversation-state)))
         (turn-summaries (and conversation-state
                              (environment-conversation-state-turns conversation-state)))
         (operation-summaries (and conversation-state
                                   (environment-conversation-state-operations conversation-state)))
         (artifact-summaries (or (environment-artifact-index environment)
                                 (and conversation-state
                                      (environment-conversation-state-artifacts conversation-state))))
         (threads (mapcar #'conversation-summary->thread thread-summaries))
         (messages (mapcar #'conversation-summary->message message-summaries))
         (turns (mapcar #'conversation-summary->turn turn-summaries))
         (operations (mapcar #'conversation-summary->operation operation-summaries))
         (artifacts (mapcar #'conversation-summary->artifact artifact-summaries)))
    (setf (agent-session-threads session) threads
          (agent-session-current-thread-id session)
          (environment-active-thread-id environment)
          (agent-session-messages session) messages
          (agent-session-turns session) turns
          (agent-session-operations session) operations
          (agent-session-artifacts session) artifacts)
    (dolist (message messages)
      (let ((thread (find-thread session (message-thread-id message))))
        (when thread
          (multiple-value-bind (ids tail)
              (append-linked-item (thread-message-ids thread)
                                  (thread-message-ids-tail thread)
                                  (message-id message))
            (setf (thread-message-ids thread) ids
                  (thread-message-ids-tail thread) tail)))))
    (dolist (turn turns)
      (let ((thread (find-thread session (turn-thread-id turn))))
        (when thread
          (multiple-value-bind (ids tail)
              (append-linked-item (thread-turn-ids thread)
                                  (thread-turn-ids-tail thread)
                                  (turn-id turn))
            (setf (thread-turn-ids thread) ids
                  (thread-turn-ids-tail thread) tail)))))
    (dolist (artifact artifacts)
      (let ((thread (and (artifact-thread-id artifact)
                         (find-thread session (artifact-thread-id artifact)))))
        (when thread
          (multiple-value-bind (ids tail)
              (append-linked-item (thread-artifact-ids thread)
                                  (thread-artifact-ids-tail thread)
                                  (artifact-id artifact))
            (setf (thread-artifact-ids thread) ids
                  (thread-artifact-ids-tail thread) tail)))))
    (dolist (operation operations)
      (let ((turn (and (operation-turn-id operation)
                       (find-turn session (operation-turn-id operation)))))
        (when turn
          (multiple-value-bind (ids tail)
              (append-linked-item (turn-operation-ids turn)
                                  (turn-operation-ids-tail turn)
                                  (operation-id operation))
            (setf (turn-operation-ids turn) ids
                  (turn-operation-ids-tail turn) tail)))))
    (dolist (artifact artifacts)
      (let ((turn (and (artifact-turn-id artifact)
                       (find-turn session (artifact-turn-id artifact)))))
        (when turn
          (multiple-value-bind (ids tail)
              (append-linked-item (turn-artifact-ids turn)
                                  (turn-artifact-ids-tail turn)
                                  (artifact-id artifact))
            (setf (turn-artifact-ids turn) ids
                  (turn-artifact-ids-tail turn) tail)))))
    session))

(defun rehydrate-session-events-from-environment (session environment)
  (let* ((environment-events (or (environment-event-log environment) '()))
         (session-events (mapcar #'environment-event->session-event environment-events))
         (transcript (loop for event in session-events
                           when (eq (event-kind event) :transcript)
                           collect (event-payload event))))
    (setf (agent-session-events session) session-events
          (agent-session-transcript session) transcript)
    session))

(defun policy-summary->capability-grant (summary)
  (make-capability-grant :policy-id (getf summary :policy-id)
                         :granted-at (getf summary :granted-at)
                         :scope (or (getf summary :scope) :session)
                         :metadata (getf summary :metadata)))

(defun rehydrate-session-capability-grants-from-environment (session environment)
  (let* ((policy-state (environment-policy-state environment))
         (grant-summaries (or (getf policy-state :capability-grants) '()))
         (grants (mapcar #'policy-summary->capability-grant grant-summaries)))
    (setf (agent-session-capability-grants session) grants)
    session))

(defun rehydrate-session-plan-from-environment (session environment)
  (let* ((agent-state (environment-agent-state environment))
         (plan (and agent-state
                    (environment-agent-state-plan agent-state))))
    (setf (agent-session-plan session) plan)
    session))

(defun rehydrate-session-pending-actions-from-environment (session environment)
  (let* ((agent-state (environment-agent-state environment))
         (pending-actions (copy-list (or (and agent-state
                                              (environment-agent-state-pending-actions agent-state))
                                         '()))))
    (setf (agent-session-pending-actions session) pending-actions)
    session))

(defun rehydrate-session-incidents-from-environment (session environment)
  (let* ((agent-state (environment-agent-state environment))
         (incidents (copy-list (or (and agent-state
                                        (environment-agent-state-incidents agent-state))
                                   '()))))
    (setf (agent-session-incidents session) incidents)
    session))

(defun rehydrate-session-tasks-and-workers-from-environment (session environment)
  (let* ((agent-state (environment-agent-state environment))
         (tasks (copy-list (or (and agent-state
                                    (environment-agent-state-tasks agent-state))
                               '())))
         (workers (copy-list (or (and agent-state
                                      (environment-agent-state-workers agent-state))
                                 '()))))
    (setf (agent-session-tasks session) tasks
          (agent-session-workers session) workers)
    session))

(defun rehydrate-session-workflow-from-environment (session environment)
  (let* ((workflow-state (environment-workflow-state environment))
         (work-items (copy-list (or (and workflow-state
                                         (environment-workflow-state-work-items workflow-state))
                                    '())))
         (workflow-records (copy-list (or (and workflow-state
                                              (environment-workflow-state-workflow-records workflow-state))
                                         '()))))
    (setf (agent-session-work-items session) work-items
          (agent-session-workflow-records session) workflow-records)
    session))

(defun make-environment-compatibility-payload-from-session (session)
  (ensure-default-thread session)
  (make-environment-compatibility-payload
   :session-id (agent-session-id session)))

(defun ensure-environment-compatibility-payload (sessionish)
  (typecase sessionish
    (environment-compatibility-payload sessionish)
    (agent-session
     (make-environment-compatibility-payload-from-session sessionish))
    (t nil)))

(defun compatibility-payload->session (payload environment)
  (let ((session (make-agent-session
                  :id (environment-compatibility-payload-session-id payload)
                  :cwd (or (environment-storage-root environment)
                           (namestring (getcwd)))
                  :package (or (getf (and (environment-runtime-state environment)
                                          (environment-runtime-state-summaries
                                           (environment-runtime-state environment)))
                                     :package)
                               "SBCL-AGENT-USER")
                  :current-thread-id (environment-active-thread-id environment)
                  :threads '()
                  :messages '()
                  :turns '()
                  :operations '()
                  :artifacts '()
                  :transcript '()
                  :events '()
                  :plan nil
                  :capability-grants '()
                  :pending-actions '()
                  :tasks '()
                  :work-items '()
                  :workflow-records '()
                  :incidents '()
                  :workers '())))
    (rehydrate-session-plan-from-environment session environment)
    (rehydrate-session-capability-grants-from-environment session environment)
    (rehydrate-session-events-from-environment session environment)
    (rehydrate-session-pending-actions-from-environment session environment)
    (rehydrate-session-incidents-from-environment session environment)
    (rehydrate-session-tasks-and-workers-from-environment session environment)
    (rehydrate-session-conversation-from-environment session environment)
    (rehydrate-session-workflow-from-environment session environment)
    (normalize-session-capability-grants session)
    (ensure-default-thread session)
    (rebuild-agent-session-tails session)
    (rebuild-conversation-tails session)
    (rebuild-workflow-record-tails session)
    (setf (agent-session-workers session)
          (serializable-worker-states session))
    (setf (agent-session-workers-tail session)
          (last (agent-session-workers session)))
    session))

(defun rehydrate-environment-derived-state (environment)
  (let* ((conversation-state (environment-conversation-state environment))
         (workflow-state (environment-workflow-state environment))
         (runtime-state (environment-runtime-state environment))
         (runtime-summaries (and runtime-state
                                 (environment-runtime-state-runtimes runtime-state)))
         (thread-summaries (and conversation-state
                                (environment-conversation-state-threads conversation-state)))
         (artifact-summaries (and conversation-state
                                  (environment-conversation-state-artifacts conversation-state)))
         (work-item-summaries (and workflow-state
                                   (mapcar #'work-item-summary
                                           (environment-workflow-state-work-items workflow-state)))))
    (setf (environment-runtime-set environment)
          (or runtime-summaries (environment-runtime-set environment))
          (environment-active-runtime-id environment)
          (or (and runtime-state
                   (environment-runtime-state-active-runtime-id runtime-state))
              (environment-active-runtime-id environment))
          (environment-thread-set environment)
          (or thread-summaries '())
          (environment-active-thread-id environment)
          (or (and conversation-state
                   (environment-conversation-state-active-thread-id conversation-state))
              (environment-active-thread-id environment))
          (environment-artifact-index environment)
          (or artifact-summaries '())
          (environment-work-item-graph environment)
          (or work-item-summaries '()))
    environment))

(defun environment-needs-sync-p (environment session)
  (let* ((summary (environment-summary environment))
         (conversation-summary (getf summary :conversation-state))
         (workflow-summary (getf summary :workflow-state))
         (agent-summary (getf summary :agent-state)))
    (or (not (string= (or (getf summary :session-id) "")
                      (or (agent-session-id session) "")))
        (not (string= (or (getf summary :storage-root) "")
                      (or (agent-session-cwd session) "")))
        (not (equal (getf summary :active-thread-id)
                    (agent-session-current-thread-id session)))
        (/= (or (getf conversation-summary :message-count) 0)
            (length (agent-session-messages session)))
        (/= (or (getf conversation-summary :turn-count) 0)
            (length (agent-session-turns session)))
        (/= (or (getf conversation-summary :operation-count) 0)
            (length (agent-session-operations session)))
        (/= (or (getf summary :artifact-count) 0)
            (length (agent-session-artifacts session)))
        (/= (length (or (environment-event-log environment) '()))
            (length (agent-session-events session)))
        (/= (or (getf workflow-summary :work-item-count) 0)
            (length (agent-session-work-items session)))
        (/= (or (getf workflow-summary :workflow-record-count) 0)
            (length (agent-session-workflow-records session)))
        (/= (or (getf agent-summary :pending-action-count) 0)
            (length (agent-session-pending-actions session)))
        (/= (or (getf agent-summary :incident-count) 0)
            (length (agent-session-incidents session)))
        (/= (or (getf agent-summary :task-count) 0)
            (length (agent-session-tasks session)))
        (/= (or (getf agent-summary :worker-count) 0)
            (length (agent-session-workers session)))
        (not (equal (getf summary :plan)
                    (agent-session-plan session)))
        (/= (length (or (getf (environment-policy-state environment) :capability-grants) '()))
            (length (agent-session-capability-grants session))))))

(defun serializable-environment-copy (environment)
  (let ((active-environment (ensure-environment environment))
        (session (environment-compatibility-session environment)))
    (when (and (compatibility-session-materialized-p session)
               (environment-needs-sync-p active-environment session))
      (sync-environment-from-session active-environment session))
    (make-environment
     :id (environment-id active-environment)
     :schema-version (environment-schema-version active-environment)
     :storage-root (environment-storage-root active-environment)
     :runtime-state (environment-runtime-state active-environment)
     :conversation-state (environment-conversation-state active-environment)
     :workflow-state (environment-workflow-state active-environment)
     :agent-state (environment-agent-state active-environment)
     :runtime-set nil
     :active-runtime-id (environment-active-runtime-id active-environment)
     :thread-set nil
     :active-thread-id (environment-active-thread-id active-environment)
     :artifact-index nil
     :work-item-graph nil
     :policy-state (environment-policy-state active-environment)
     :agent-registry (environment-agent-registry active-environment)
     :memory (environment-memory active-environment)
     :summaries (environment-summaries active-environment)
     :event-log (environment-event-log active-environment)
     :compatibility-session (ensure-environment-compatibility-payload session)
     :metadata (environment-metadata active-environment))))

(defun save-environment (environment path)
  (with-open-file (stream path
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create)
    (let ((*print-circle* t)
          (*print-pretty* t)
          (*print-length* nil)
          (*print-level* nil)
          (*print-lines* nil)
          (*print-right-margin* nil))
      (write (serializable-environment-copy environment) :stream stream)))
  path)

(defun load-environment (path)
  (with-open-file (stream path :direction :input)
    (let ((environment (read stream nil nil)))
      (unless (typep environment 'environment)
        (error "Environment file ~A did not contain an ENVIRONMENT" path))
      (let ((session (environment-compatibility-session environment)))
        (when (and session (typep session 'agent-session))
          (normalize-session-capability-grants session)
          (ensure-default-thread session)
          (rebuild-agent-session-tails session)
          (rebuild-conversation-tails session)
          (rebuild-workflow-record-tails session)
          (setf (agent-session-workers session)
                (serializable-worker-states session))
          (setf (agent-session-workers-tail session)
                (last (agent-session-workers session)))))
      (normalize-kernel-execution-registry-for-load environment)
      (rehydrate-environment-derived-state environment)
      (setf (environment-compatibility-session environment)
            (ensure-environment-compatibility-payload
             (environment-compatibility-session environment)))
      (setf *current-environment* environment)
      (let ((session (environment-compatibility-session environment)))
        (when (typep session 'agent-session)
          (setf *current-session* session)))
      environment)))
