(in-package #:sbcl-agent)

(defun json-whitespace-char-p (character)
  (find character '(#\Space #\Tab #\Newline #\Return)))

(defun json-skip-whitespace (string index)
  (loop while (and (< index (length string))
                   (json-whitespace-char-p (char string index)))
        do (incf index)
        finally (return index)))

(defun json-parse-string (string index)
  (unless (char= (char string index) #\")
    (error "Expected JSON string at index ~D" index))
  (incf index)
  (let ((buffer (make-string-output-stream)))
    (loop while (< index (length string))
          for character = (char string index)
          do (cond
               ((char= character #\\)
                (incf index)
                (when (>= index (length string))
                  (error "Unterminated JSON escape"))
                (let ((escaped (char string index)))
                  (write-char
                   (case escaped
                     (#\" #\")
                     (#\\ #\\)
                     (#\/ #\/)
                     (#\b #\Backspace)
                     (#\f #\Page)
                     (#\n #\Newline)
                     (#\r #\Return)
                     (#\t #\Tab)
                     (t (error "Unsupported JSON escape ~C" escaped)))
                   buffer)))
               ((char= character #\")
                (return-from json-parse-string
                  (values (get-output-stream-string buffer) (1+ index))))
               (t
                (write-char character buffer)))
             (incf index))
    (error "Unterminated JSON string")))

(defun json-parse-number (string index)
  (let ((start index))
    (loop while (and (< index (length string))
                     (find (char string index) "+-0123456789.eE"))
          do (incf index))
    (values (read-from-string (subseq string start index)) index)))

(defun json-parse-literal (string index literal value)
  (let ((end (+ index (length literal))))
    (unless (and (<= end (length string))
                 (string= literal string :start2 index :end2 end))
      (error "Expected JSON literal ~A at index ~D" literal index))
    (values value end)))

(defun json-parse-array (string index)
  (unless (char= (char string index) #\[)
    (error "Expected JSON array at index ~D" index))
  (incf index)
  (let ((values '()))
    (loop
      (setf index (json-skip-whitespace string index))
      (when (>= index (length string))
        (error "Unterminated JSON array"))
      (when (char= (char string index) #\])
        (return (values (nreverse values) (1+ index))))
      (multiple-value-bind (value next-index)
          (json-parse-value string index)
        (push value values)
        (setf index (json-skip-whitespace string next-index))
        (cond
          ((char= (char string index) #\,)
           (incf index))
          ((char= (char string index) #\])
           (return (values (nreverse values) (1+ index))))
          (t
           (error "Expected ',' or ']' in JSON array at index ~D" index)))))))

(defun json-parse-object (string index)
  (unless (char= (char string index) #\{)
    (error "Expected JSON object at index ~D" index))
  (incf index)
  (let ((pairs '()))
    (loop
      (setf index (json-skip-whitespace string index))
      (when (>= index (length string))
        (error "Unterminated JSON object"))
      (when (char= (char string index) #\})
        (return (values (nreverse pairs) (1+ index))))
      (multiple-value-bind (key next-index)
          (json-parse-string string index)
        (setf index (json-skip-whitespace string next-index))
        (unless (char= (char string index) #\:)
          (error "Expected ':' after JSON object key at index ~D" index))
        (incf index)
        (setf index (json-skip-whitespace string index))
        (multiple-value-bind (value value-index)
            (json-parse-value string index)
          (push (cons key value) pairs)
          (setf index (json-skip-whitespace string value-index))
          (cond
            ((char= (char string index) #\,)
             (incf index))
            ((char= (char string index) #\})
             (return (values (nreverse pairs) (1+ index))))
            (t
             (error "Expected ',' or '}' in JSON object at index ~D" index))))))))

(defun json-parse-value (string index)
  (setf index (json-skip-whitespace string index))
  (when (>= index (length string))
    (error "Unexpected end of JSON input"))
  (case (char string index)
    (#\{ (json-parse-object string index))
    (#\[ (json-parse-array string index))
    (#\" (json-parse-string string index))
    (#\t (json-parse-literal string index "true" t))
    (#\f (json-parse-literal string index "false" nil))
    (#\n (json-parse-literal string index "null" :null))
    (t (json-parse-number string index))))

(defun parse-json (string)
  (multiple-value-bind (value index)
      (json-parse-value string 0)
    (declare (ignore index))
    value))

(defun json-escape-string (string)
  (with-output-to-string (out)
    (loop for character across string
          do (case character
               (#\" (write-string "\\\"" out))
               (#\\ (write-string "\\\\" out))
               (#\Newline (write-string "\\n" out))
               (#\Return (write-string "\\r" out))
               (#\Tab (write-string "\\t" out))
               (t (write-char character out))))))

(defun keyword->json-key (keyword)
  (string-downcase (substitute #\_ #\- (symbol-name keyword))))

(defun json-plist-p (value)
  (and (listp value)
       (evenp (length value))
       (loop for (key val) on value by #'cddr
             always (and (keywordp key)
                         (or val t)))))

(defun json-write-value (value stream)
  (cond
    ((eq value :null)
     (write-string "null" stream))
    ((stringp value)
     (format stream "\"~A\"" (json-escape-string value)))
    ((eq value t)
     (write-string "true" stream))
    ((null value)
     (write-string "false" stream))
    ((numberp value)
     (princ value stream))
    ((json-plist-p value)
     (write-char #\{ stream)
     (loop for (key val) on value by #'cddr
           for first = t then nil
           do (unless first (write-char #\, stream))
              (format stream "\"~A\":" (json-escape-string (keyword->json-key key)))
              (json-write-value val stream))
     (write-char #\} stream))
    ((listp value)
     (write-char #\[ stream)
     (loop for item in value
           for first = t then nil
           do (unless first (write-char #\, stream))
              (json-write-value item stream))
     (write-char #\] stream))
    (t
     (error "Unsupported JSON value ~S" value))))

(defun emit-json (value)
  (with-output-to-string (stream)
    (json-write-value value stream)))

(defun json-object-value (object key)
  (cdr (assoc key object :test #'string=)))
